### ISSUE TITLE
owner - partnership

### ISSUE THREAD

**Issue by dutchTender** [GrantThorntonETSI/eFile_Reimagined#103]
this has a form field that is  a list of values. requires dynamic form binding

**Comment by JackieBabos** [comment]
![general partner partnership drop down](https://user-images.githubusercontent.com/44168600/49248784-87234d00-f3e8-11e8-8713-64ca9473b352.PNG)

**Comment by dutchTender** [comment]
add "manged contact" to each user ....(this managed contact will just be user's own information) and this will be attached to each account.( in this iteration, there is no way for the client to create additional managed contacts" ...all owner contacts and attorney contacts are created for the application object, and are not directly attached to the PTO user object.   this in-effect will allow the  "managed contact" to be used in all applications, but owners and attorneys created for each application will only belong to that application.
