### ISSUE TITLE
Mark Type 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#122]
The text below will need to be placed after the "expand for uncommon mark types" and then above the mark tiles. 

**Which of the following types best describes the mark you want to apply for?**

![text missing](https://user-images.githubusercontent.com/44168600/49818616-334a2980-fd41-11e8-9875-3c4834977480.PNG)

**Comment by JackieBabos** [comment]
Also I am not sure if you or Lynn update this. 

But the Design with Text tile should have the A on it, so the Design Only should have the A removed and be placed on the Design with Text tile.  (The image above, or the one in UXPin is correct)

The image below is incorrect. 
![design with text](https://user-images.githubusercontent.com/44168600/49819089-807acb00-fd42-11e8-8551-15f2f51adfb3.PNG)

**Comment by JackieBabos** [comment]
Also Motion with Text on the "Examples Page" is incorrect. It needs to have the below images inserted in there instead. 
![design with text](https://user-images.githubusercontent.com/44168600/49819976-af923c00-fd44-11e8-99d8-8be2d9916752.PNG)
![motion with text2](https://user-images.githubusercontent.com/44168600/49819975-af923c00-fd44-11e8-95eb-06a63231e0f1.png)

**Comment by dutchTender** [comment]
i would allocate this to Lynn. since she has better knowledge then i don on these new pages and how to make changes to them.

**Comment by l-stanny** [comment]
> Also Motion with Text on the "Examples Page" is incorrect. It needs to have the below images inserted in there instead. The image is already being used in "motion"....
> 
> ![motion with text2](https://user-images.githubusercontent.com/44168600/49819988-bcaf2b00-fd44-11e8-886a-1301784b13f9.png)
> http://tsdr.uspto.gov/#caseNumber=78832765&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch
> 
> ![motion with text1](https://user-images.githubusercontent.com/44168600/49819995-c173df00-fd44-11e8-9655-42c13edfde76.png)
> http://tsdr.uspto.gov/#caseNumber=86024088&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch

**Comment by l-stanny** [comment]
<img width="807" alt="screen shot 2019-01-02 at 4 44 38 am" src="https://user-images.githubusercontent.com/8275852/50586799-294fae00-0e49-11e9-8877-f579e3c57e36.png">
This has been completed locally
