### ISSUE TITLE
Black and White Image - Color Claim "No"

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#128]
When the user says no to color claim. Have the ability to have the picture that the user uploaded and change it from full color to either black and white and grayscale. 

![image](https://user-images.githubusercontent.com/44168600/49955687-75a27080-fed1-11e8-9c24-af3ee7b0504b.png)

**Comment by dutchTender** [comment]
I will start the back end functionality for this ..
