### ISSUE TITLE
Remove the "Confirm button" after selecting the attorney

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#129]
![image](https://user-images.githubusercontent.com/44168600/49956325-e8f8b200-fed2-11e8-94f4-390bb78427f7.png)

**Comment by dutchTender** [comment]
we will need two next buttons here, one is a submit, and one is a real next button ... i guess we can hide them based on if required fields are not empty or null ... @l-stanny  what do you think???  but lets talk about this after the monday acceptance by the client of the new UI changes

**Comment by dutchTender** [comment]
new button toggle next for submit.

**Comment by l-stanny** [comment]
Completed
