### ISSUE TITLE
Remove the text box after clicking "No" for Translation

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#130]
![image](https://user-images.githubusercontent.com/44168600/49957039-b485f580-fed4-11e8-9f21-1d57529b088d.png)

**Comment by l-stanny** [comment]
<img width="762" alt="screen shot 2019-01-02 at 9 56 42 pm" src="https://user-images.githubusercontent.com/8275852/50622230-9ad73d00-0ed9-11e9-8a57-048437f89335.png">
Completed, will be in the next repository upload
