### ISSUE TITLE
Personal Information 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#135]
Bold, “Personal Information” on the gray bar. Remove the title line. 
![image](https://user-images.githubusercontent.com/44168600/50098350-b9ef8280-01e9-11e9-8689-17a0ec369002.png)

**Comment by dutchTender** [comment]
I noticed that the two gray bars above this one like two step and sign in also don't have bold text, should we update those two as well?

**Comment by dutchTender** [comment]
I will put the latest build on stage tomorrow morning. just send me a message when the issue can be closed.
