### ISSUE TITLE
E-Mail wording

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#137]
Change the E-Mail to “Email Address”

![image](https://user-images.githubusercontent.com/44168600/50098655-59ad1080-01ea-11e9-9a60-a5187c2f5a82.png)

**Comment by JackieBabos** [comment]
Also remove the "Email" formatted text that is inside the Email Address text box

**Comment by JackieBabos** [comment]
Remove the formatted text within the text boxes. 
![image](https://user-images.githubusercontent.com/44168600/50099020-1dc67b00-01eb-11e9-8741-252fac7cd24d.png)

**Comment by dutchTender** [comment]
i will get this tonight as well.
