### ISSUE TITLE
Gray out "Other" on US entity types

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#140]
**Scroll to bottom of this page for the task.**

After the user selects "Other" on US entity page. More options appear, but forms won't appear. 

![image](https://user-images.githubusercontent.com/44168600/50103639-1193eb00-01f6-11e9-8c8d-ac28c0db4e16.png)

**The list below are the options:**
Corporation, Association, Organization, and Company
Trusts, Conservatorship, and Estates
Business Trusts
Governmental Bodies and Universities
Banking Institutions
Federally Recognized Indian Tribe
State Recognized Indian Tribe
Limited Liability Partnerships
Congressionally Charted Non-Profit Organization
Manually Enter
![image](https://user-images.githubusercontent.com/44168600/50103784-6df70a80-01f6-11e9-8055-035a780a7d44.png)

**Comment by dutchTender** [comment]
@l-stanny  this is a good example of the pattern eFile wants their forms to load. essentially from one page ...you have the ability to load 30 to 40 different type of forms ......these are new requirements. right now we only have one select menu that drives the pages to be loaded.
currently i am using  Ajax to load pages based the value of select menu

**Comment by JackieBabos** [comment]
Was there a reason why you closed this? If we don't want to do this, we need to gray out "Other" under the U.S. entity so the user doesn't click on it to a blank screen.

![image](https://user-images.githubusercontent.com/44168600/52794206-593fc300-303d-11e9-992c-0a7cbad16fb7.png)

**Comment by JackieBabos** [comment]
Need clarification from the BAs on what they want displayed.

**Comment by JackieBabos** [comment]
Gray out the "Other" entity type so the user can't click on it. 

![image](https://user-images.githubusercontent.com/44168600/53188190-d4235380-35d2-11e9-8dc9-2a7338939399.png)

**Comment by dutchTender** [comment]
i ll get this next

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/53973447-c1c71080-40ce-11e9-91d4-1e397d721365.png)
