### ISSUE TITLE
Email address not be case sensitive

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#143]
When a user is logging in, the email address should not be case sensitive

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50242300-e943f200-0397-11e9-9a41-3cf7223d11e0.png)

**Comment by dutchTender** [comment]
are you saying on this page?

**Comment by dutchTender** [comment]
store the email tied to accounts to be case- insensitive
