### ISSUE TITLE
Homepage Alert Banner color change

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#148]
The warning banner across the top should be a light shade of red/pink. The outline should not be as bold.  

https://uspto.github.io/designpatterns/1.x/docs/components/alerts.html

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/50239561-8ac74580-0390-11e9-91b9-47bb187c6a2a.png)

**Comment by dutchTender** [comment]
change the bar to blue, add info 'icon', 

    background-color: #e8f5fa;
    border-color: #d0dce1;
    color: #444;
(use this icon)
<i class="alert-icon alert-icon-info"></i>

**Comment by dutchTender** [comment]
<i class="alert-icon alert-icon-info"></i>

**Comment by dutchTender** [comment]
//<i class="alert-icon alert-icon-info"></i>//

**Comment by dutchTender** [comment]
class="alert-icon alert-icon-info

**Comment by dutchTender** [comment]
check back here for system messages and notifications.

**Comment by dutchTender** [comment]
also added close button, so that the user can make the alert banner fade out.
