### ISSUE TITLE
REORDER USER ACCOUNT PAGE

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#154]
User Profile (Rename it from User Account) 
Include the message: Complete your user profile. 

Rearrange the information to match the order below:

Account Information 
Contact information
System Account Preferences - (Currently "Sign In")
Set up Two-factor Authentication (Required that they choose one - gray out the cell phone)
Account View (Gray out experienced view)

**Comment by dutchTender** [comment]
rename personal information to account information
