### ISSUE TITLE
Change Account Password screen 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#156]
![image](https://user-images.githubusercontent.com/44168600/50249270-7e9cb180-03ab-11e9-9da1-448d72cd068a.png)

1.	The Cancel and Update buttons should not have the thumbs up or down image.  That’s standard for Like and Dislike, which doesn’t make sense in this case. The buttons should follow the standard.
2.	Password in gray in the text input box is not needed.  
3.	Do not user the colons.  They are not used anywhere else.

![image](https://user-images.githubusercontent.com/44168600/50249286-8bb9a080-03ab-11e9-8113-61f05fee9bd7.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50363932-f39ef100-053b-11e9-8f72-912335d6190d.png)

**Comment by dutchTender** [comment]
@JackieBabos  do we need to the log in modal like your screen shot? or was that just to show the "save" and "cancel" buttons.  meaning do i need to add a third field for confirm new password, and image showing password minimum requirement. right now i believe we are only enforcing password to be 5 characters long.

**Comment by JackieBabos** [comment]
The current screen is the screenshot below. But will be reworked when Lynn restyles this page. 

![image](https://user-images.githubusercontent.com/44168600/52656135-b6b00480-2ec3-11e9-8fe3-4c889318e395.png)
