### ISSUE TITLE
Terms of Use and Privacy Policy

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#157]
When clicking the link to the policies, they should open in a browser new tab to be consistent with MyUSPTO.

![image](https://user-images.githubusercontent.com/44168600/50249905-5d3cc500-03ad-11e9-8cbc-483d9381064a.png)

Link for Terms of Use:
https://www.uspto.gov/terms-use-uspto-websites 

Link for Privacy Policy:
https://www.uspto.gov/privacy-policy

**Comment by JackieBabos** [comment]
1.	Terms of User and Privacy Policy, should be right above the submit button.  (see below)
2.     The submit button should read "Next"

![image](https://user-images.githubusercontent.com/44168600/50250279-595d7280-03ae-11e9-9952-76cb7ea89902.png)

**Comment by JackieBabos** [comment]
Make the Terms of User and Privacy Policy open in a new tab, not as a modal.

**Comment by JackieBabos** [comment]
Have the links in the bottom right hand corner work as well.

![image](https://user-images.githubusercontent.com/44168600/50304386-ce3bb580-045d-11e9-8fa0-3a39587b35f1.png)

**Comment by dutchTender** [comment]
this have been updated in the latest build. the term of use and privacy policy are now links to myuspto pages.

**Comment by JackieBabos** [comment]
Can the pages be open in new windows?

**Comment by l-stanny** [comment]
@serra-trinh @dutchTender This issue has been resolved locally and pushed to GitHub 03/13/2019.

**Comment by l-stanny** [comment]
@serra-trinh @dutchTender This issue has been resolved locally and pushed to GitHub 03/13/2019.

**Comment by dutchTender** [comment]
links on registration page now open in a new window.
