### ISSUE TITLE
* indicates required - missing

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#159]
* indicates required is missing from the page on the create account page

![image](https://user-images.githubusercontent.com/44168600/50251178-0fc25700-03b1-11e9-8261-4931c6cb0e9f.png)

**Comment by JackieBabos** [comment]
Asterisks should be on the right side of the word when the labels are vertically aligned and in the same color as the font

https://uspto.github.io/designpatterns/1.x/docs/components/forms.html#required-fields

**Comment by dutchTender** [comment]
done. i will close this after the demo
