### ISSUE TITLE
Make input boxes less rounded - radius 2px

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#160]
Use radius 2px

The input text boxes and drop downs are rounded, however, throughout the application they are square.  See design library and My USPTO.

https://uspto.github.io/designpatterns/1.x/docs/components/forms.html#required-fields

**Comment by dutchTender** [comment]
i got this for the registration page. i will do it through out the application. this can be closed after the demo.
