### ISSUE TITLE
Image appear in the box when the user uploads their mark

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#162]
When a user uploads their mark, the image needs to show here in the box, before going to the next screen. 

![image](https://user-images.githubusercontent.com/44168600/50292472-3038f280-043f-11e9-9f39-7f2a83c207cc.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50358741-58505080-0528-11e9-875c-1dd59f160ddb.png)
