### ISSUE TITLE
General UI comments

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#163]
1.	The font should be:  
a.	Segoe UI: Ships with Windows Vista and newer and Microsoft Office.
b.	Helvetica Neue: Ships with OSX.
2.	All Input text boxes are too rounded on the edges.  Should be more rectangular with a slight curve.  https://uspto.github.io/designpatterns/1.x/docs/components/forms.html#required-fields 
3.	The required indicator should be the same color as the font, and should be to the right of the word if the labels are vertically aligned.  https://uspto.github.io/designpatterns/1.x/docs/components/forms.html#required-fields 
4.	All buttons when enabled, should turn a darker shade of blue when hovered over
5.	All blue buttons when disabled should be a lighter color blue.  A red circle with a line through it should appear when hovered over.  
6.	All of the buttons on the bottom of the screen should be responsive and adjust to the content on the screen.
7.	Spacing of fields across the entire application should be addressed to minimize the scrolling and use of so much real estate on the pages.
8.	Only the first word of the each sentence should be capitalized, including on headers

**Comment by JackieBabos** [comment]
The info circle should look like this:
https://uspto.github.io/designpatterns/1.x/docs/foundation/icons.html

https://fontawesome.com/icons?d=gallery&m=free
info-circle

**Comment by l-stanny** [comment]
@JackieBabos My Github notifications were not getting into my Inbox at the time this was written, I'll go through and make sure all of these issues are addressed

**Comment by l-stanny** [comment]
![screen shot 2019-02-28 at 4 06 24 pm](https://user-images.githubusercontent.com/8275852/53598505-ee30d900-3b72-11e9-84c7-9f475ad4f0ce.png)
Validated: Font-family is correct.

**Comment by l-stanny** [comment]
![screen shot 2019-02-28 at 4 09 14 pm](https://user-images.githubusercontent.com/8275852/53598629-3cde7300-3b73-11e9-9820-d930b440a409.png)
Validated: All Input fields, except select menus, are slightly rounded. Select menus will require customization if too rounded.

**Comment by l-stanny** [comment]
![screen shot 2019-02-28 at 4 12 06 pm](https://user-images.githubusercontent.com/8275852/53598805-a2326400-3b73-11e9-9d4c-cef1f677ff5e.png)
Validated locally: All buttons when enabled, should turn a darker shade of blue when hovered over.
![screen shot 2019-02-28 at 4 11 55 pm](https://user-images.githubusercontent.com/8275852/53598810-a2cafa80-3b73-11e9-9f50-eab7fd3b2c69.png)dated

**Comment by l-stanny** [comment]
I believe this is implemented locally, please clarify if necessary: All of the buttons on the bottom of the screen should be responsive and adjust to the content on the screen.

**Comment by l-stanny** [comment]
I believe this is implemented correctly locally, please clarify if not: Spacing of fields across the entire application should be addressed to minimize the scrolling and use of so much real estate on the pages.

**Comment by l-stanny** [comment]
@JackieBabos Is any of this example incorrect? Only the first word of the each sentence should be capitalized, including on headers

![screen shot 2019-02-28 at 4 16 38 pm](https://user-images.githubusercontent.com/8275852/53599083-57651c00-3b74-11e9-945b-468c23f71ad7.png)

**Comment by l-stanny** [comment]
I believe this is implemented as required locally: The info circle should look like this:
https://uspto.github.io/designpatterns/1.x/docs/foundation/icons.html
https://fontawesome.com/icons?d=gallery&m=free
![screen shot 2019-02-28 at 4 20 57 pm](https://user-images.githubusercontent.com/8275852/53599329-ef630580-3b74-11e9-8234-ebc7727a6a1a.png)
![screen shot 2019-02-28 at 4 20 45 pm](https://user-images.githubusercontent.com/8275852/53599331-effb9c00-3b74-11e9-84c9-db44651f3c04.png)

info-circle

**Comment by l-stanny** [comment]
@JackieBabos This has been completed locally and will be in the next GitHub push: The required indicator should be the same color as the font, and should be to the right of the word if the labels are vertically aligned. https://uspto.github.io/designpatterns/1.x/docs/components/forms.html#required-fields

**Comment by l-stanny** [comment]
@JackieBabos This has been completed locally and will be in the next GitHub push :All blue buttons when disabled should be a lighter color blue.

**Comment by l-stanny** [comment]
@JackieBabos This has been completed locally and will be in the next GitHub push: A red circle with a line through it should appear when hovered over.

**Comment by l-stanny** [comment]
@dutchTender These changes are in this morning's GitHub push. Note: there is a questions re: capitalization, so no changes have been made on that

**Comment by JackieBabos** [comment]
All are completed in this list, besides #166, but that was completed in its own issue.
