### ISSUE TITLE
Only the first word of the each sentence should be capitalized

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#166]
Only the first word of the each sentence should be capitalized. On the login page as well as the new user account page. This should be done throughout the entire application. 

- First name, Last name, etc.
- Select application view for new applications
- Guided user view, etc

**Comment by l-stanny** [comment]
@jbabos This is part of Issue #163: Can you please confirm that in the screen capture, The headlines in the bars needs to be changed (such as Attorney information) as well as form labels (such as Middle name)
![screen shot 2019-02-28 at 4 16 38 pm](https://user-images.githubusercontent.com/8275852/53606172-dca5fc00-3b87-11e9-88f8-7399e66bde4b.png)
onfirm that the

**Comment by JackieBabos** [comment]
@keytie Double checking if you would still like us to do this? Thanks!

**Comment by nguyenvivi** [comment]
Yes, please.

~Keyte

**Comment by JackieBabos** [comment]
@keytie @nguyenvivi 

Would you like this to be applied to the gray bar titles as well?
![image](https://user-images.githubusercontent.com/44168600/53822952-c066de00-3f3e-11e9-9c54-832a6c26c671.png)

So it becomes "Attorney information"?

**Comment by nguyenvivi** [comment]
Please leave the heading as is.

**Comment by l-stanny** [comment]
Local files have been updated
- Nav and Headline content is unchanged
- Select menus with entity type (Sole Proprietorship, etc.) is unchanged
- Normally capitalized content 9State, Country, Language, etc.) is unchanged
- Select menus containing UPPERCASE countries have been changed

**Comment by l-stanny** [comment]
Completed locally, to update server-ready files
