### ISSUE TITLE
different header and footer for public facing page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#167]
![image](https://user-images.githubusercontent.com/44168600/50299640-1653db80-0450-11e9-8bc7-87da095e1d47.png)

This is the page that would be on the USPTO.gov site (under Trademarks), therefore the header and footer should be the same as the USPTO.gov site, not the MyUSPTO site.  

Header
![image](https://user-images.githubusercontent.com/44168600/50299646-1d7ae980-0450-11e9-9bba-8b40ba122987.png)

Footer
![image](https://user-images.githubusercontent.com/44168600/50299649-1fdd4380-0450-11e9-9bf1-f5f99245ec04.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50312356-1070f100-0476-11e9-8bd1-bedfd4c8d031.png)

**Comment by dutchTender** [comment]
@JackieBabos  I am not really sure how to fit the rest of the screen in .... as the uspto header also include this image menu that extends down from the header .....  but we can discuss this during our stand up tomorrow ...

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50313182-90985600-0478-11e9-910f-6aabe9dca35f.png)
 we probably need to do their entire page .... i don't think this header fits well with what we currently have.

**Comment by dutchTender** [comment]
this is on the stage server. we can reference it when we talk about in the stand up
