### ISSUE TITLE
Remove the sticky footer

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#168]
Remove the sticky footer. 

![image](https://user-images.githubusercontent.com/44168600/50302833-494e9d00-0459-11e9-9163-984d7f553a0b.png)

**Comment by dutchTender** [comment]
@l-stanny @JackieBabos @jgoldstein02  lets talk about this during our stand up ...i tried this initially, and saw some problems ...this should be thought about with the placement of the new application buttons in mind .., but i will post a screen shot of the issue of none fixed footer

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/50311141-2aa8d000-0472-11e9-8b3d-b2ed620783fa.png)
