### ISSUE TITLE
Add Additional Buttons

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#177]
This is currently in our backlog.

Make sure if there are "add additional" buttons that they work, if not gray them out to show they aren't functional. 

Once the functionality is added it will need to work for adding another phone number, and docket.

**Comment by dutchTender** [comment]
@l-stanny can you look into this? this is essentially injecting new fields into a form. you may get an account on myuspto.gov and see how this works on their site.

**Comment by l-stanny** [comment]
@dutchTender 
![screen shot 2019-03-05 at 12 34 30 am](https://user-images.githubusercontent.com/8275852/53818452-15eabd00-3f36-11e9-8de4-7eb5772b000d.png)
In the screen capture are the currently remaining add /remove instances that are in production. All others (i.e.: phone, docket, foreign reg, foreign application) have been completed locally and are in GitHub.

**Comment by l-stanny** [comment]
@dutchTender @JackieBabos The add + delete components have been completed in the local files and the last of them have been uploaded to GitHub (Name, Portrait, Signature, Translate and Transliterate.

**Comment by l-stanny** [comment]
@dutchTender Marks Design w/Text Translate and Transliterate sections never had Add + Delete Components. Checked w/ @JackieBabos and updated the file accordingly, pushed to GitHub.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/55016377-3e555c80-4fb4-11e9-8340-f10a2ed5f43e.png)
![image](https://user-images.githubusercontent.com/44168600/55016395-47dec480-4fb4-11e9-9dee-4c0a52235786.png)
