### ISSUE TITLE
Attorney Email and Name overlapping on confirmation page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#183]
The text in the Attorney information overlaps each other.  See the email address and the firm name in the screenshot below.

![image](https://user-images.githubusercontent.com/44168600/50455293-0c801b80-091b-11e9-8a3e-216f554bd5fd.png)

**Comment by dutchTender** [comment]
fixed in last update. will add to owner as well.
