### ISSUE TITLE
Meaning/Significance

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#186]
Missing information, needs to have the second line and text box. 

currently:
![image](https://user-images.githubusercontent.com/44168600/50457105-1f005200-0927-11e9-9b4f-203d242aee04.png)

needs to be:
![image](https://user-images.githubusercontent.com/44168600/50457095-0db74580-0927-11e9-901f-15fe886d93ab.png)

**Comment by dutchTender** [comment]
let me check lynn's latest html. i added this a while back.

**Comment by dutchTender** [comment]
ok, its missing in the latest html as well

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/51493772-5d512b80-1d84-11e9-876b-ba1bf67e7d42.png)
