### ISSUE TITLE
Phone number not required

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#187]
"Phone Number is not a required data" 

Remove the asterik. 

![image](https://user-images.githubusercontent.com/44168600/50457129-5ec73980-0927-11e9-9062-630b20d80cff.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53112810-1cc50900-350e-11e9-96a4-3b01ae6c62f1.png)
made phone number not required

**Comment by nguyenvivi** [comment]
Complete.
