### ISSUE TITLE
Table title alignment/formatting - Filings/Applications

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#189]
The table title should be aligned with the "New Application" button.  
The "New Application" button should be right justified with the row.  The title box can then be made smaller to get rid of all the wasted space.
![home1](https://user-images.githubusercontent.com/45850524/50481184-2d458100-09ae-11e9-80d6-fc3b076a2ecc.jpg)

**Comment by keytie** [comment]
This applies to the Upcoming Actions Due widget, too.
![2018-12-27_8-06-36](https://user-images.githubusercontent.com/45850524/50481220-60881000-09ae-11e9-9a39-e4577b8ba193.jpg)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/55017257-f800fd00-4fb5-11e9-9b95-b209efa264c9.png)

**Comment by nguyenvivi** [comment]
We can close this issue.
