### ISSUE TITLE
Too much white space between Titles, questions, labels, text boxes - Attorney

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#190]
There is too much space between the question and the Attorney information section.  There is also too much white space between titles, sections, questions, etc.  This information could be better laid out so that it fits without having to scroll so much.

As an example, I highlighted all the empty space that could be removed to reduce all the scrolling.
![2018-12-27_8-07-43](https://user-images.githubusercontent.com/45850524/50481333-e99f4700-09ae-11e9-819b-856c993126bc.jpg)

**Comment by dutchTender** [comment]
no longer an issue with new header and footer.
