### ISSUE TITLE
Change Managed Contacts button

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#191]
Change the text in the button from Fill from Managed Contacts to Select from contacts.
![2018-12-27_8-13-56](https://user-images.githubusercontent.com/45850524/50481420-603c4480-09af-11e9-8f07-97ececf95b55.jpg)

**Comment by JackieBabos** [comment]
Change the widget on the bottom title to "Select from contacts"

**Comment by dutchTender** [comment]
will do.
