### ISSUE TITLE
Check not properly appearing in the box - Certification in good standing

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#192]
The check is not in the center of the box:

![2018-12-27_8-13-56](https://user-images.githubusercontent.com/45850524/50481517-fd977880-09af-11e9-9740-bfea2d428f0c.jpg)

**Comment by JackieBabos** [comment]
located in 'attorney_info_m010'

![image](https://user-images.githubusercontent.com/44168600/52306667-8ff34a80-2966-11e9-8838-3ac551b04b6a.png)
