### ISSUE TITLE
The font should be the same size for all questions.  

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#193]
The font for "Upload bar credentials, including...." is smaller than the rest of the font on this page.  It should be the same.

![2018-12-27_8-13-56](https://user-images.githubusercontent.com/45850524/50481607-7c8cb100-09b0-11e9-90c1-f3466eb583a6.jpg)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/50835241-2e6a9c80-1324-11e9-87d0-4b20c574771b.png)

The "Upload bar credentials" was placed in side the upload box, let me know if you want it to be located outside of it.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/65255801-c0ce5d00-dabb-11e9-8b7c-66d08653043b.png)

This issue was resolved when we made the upload instructions consistent throughout the application.
