### ISSUE TITLE
Swap Acknowledgement with Bar Credentials upload

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#194]
Move the upload of the bar credentials before the acknowledgement of certification in good standing.
![2018-12-27_8-13-56](https://user-images.githubusercontent.com/45850524/50481666-c4abd380-09b0-11e9-909c-c9f0278c9b3f.jpg)

**Comment by l-stanny** [comment]
@JackieBabos @serra-trinh @dutchTender This has been completed locally and will be included in the next GitHub push.
![Screen Shot 2019-03-14 at 5 45 13 PM](https://user-images.githubusercontent.com/8275852/54393664-18a98880-4681-11e9-97f1-657236a33b3d.png)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/65253359-c164f480-dab7-11e9-9388-7d3654f83310.png)

This has been completed.
