### ISSUE TITLE
Collapsible Panels

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#195]
The up/down arrows is used to collapse/expand the panels on the first level (but they are typically used for moving something up or down, like moving the attorney up or down in that list, not expanding/collapsing panels).  However, ‘>’ is used in the lower drilled down levels.  This should be consistent.  The collapsible panel icons should look and perform like these (https://uspto.github.io/designpatterns/1.x/docs/components/collapsiblePanels.html

![people](https://user-images.githubusercontent.com/45850524/50481786-777c3180-09b1-11e9-94ed-2cdeacbb517c.png)

**Comment by dutchTender** [comment]
I will change this to right arrow.

**Comment by JackieBabos** [comment]
We need to add a collapsible arrow, so the user knows they can expand the users information 

![image](https://user-images.githubusercontent.com/44168600/52802265-97dd7980-304d-11e9-9532-3b11a93c55e3.png)

**Comment by l-stanny** [comment]
Updated local files for Attorney Edit and Owner Edit to compensate for server needs on these two pages. Pushed to GitHub. Updated application files for server (HTML, jQuery, CSS), uploaded to GT OneDrive filename 019_0410_eFile_Reimagined-master.zip
<img width="1367" alt="Screen Shot 2019-04-10 at 8 16 52 PM" src="https://user-images.githubusercontent.com/8275852/55922222-3a3d5780-5bce-11e9-8ecb-5364d2bcf02c.png">
<img width="1366" alt="Screen Shot 2019-04-10 at 8 16 43 PM" src="https://user-images.githubusercontent.com/8275852/55922223-3ad5ee00-5bce-11e9-877e-e9c3fda3b556.png">
<img width="1094" alt="Screen Shot 2019-04-10 at 8 21 48 PM" src="https://user-images.githubusercontent.com/8275852/55922256-55a86280-5bce-11e9-97ef-06aad0a9f94d.png">
