### ISSUE TITLE
Primary Attorney text is scrunched up 

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#198]
The below text should be able to fit on one line.  I'm not sure why it keeps wrapping after a few words.

![2018-12-27_8-35-28](https://user-images.githubusercontent.com/45850524/50482217-9b407700-09b3-11e9-8e3c-8184ed434ed9.jpg)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/52293888-ed2ad400-2945-11e9-9bdc-59d9fa00706b.png)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/53040573-b37ec080-344f-11e9-8062-d1e87b8eb645.png)
![image](https://user-images.githubusercontent.com/44168600/53040597-c0031900-344f-11e9-90cd-864a4b530142.png)
