### ISSUE TITLE
A space is missing - Affiliation Information

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#201]
There should be a space between in and Canada:

![home1](https://user-images.githubusercontent.com/45850524/50482557-2d954a80-09b5-11e9-9fc3-0ec66860f26f.jpg)

**Comment by JackieBabos** [comment]
Lynn completed, located in 'attorney_info_m010'

![image](https://user-images.githubusercontent.com/44168600/52306305-9208d980-2965-11e9-9948-c2a54772539c.png)
