### ISSUE TITLE
Checkbox does not work - Affiliation Information

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#202]
I am unable to check the box.

![home1](https://user-images.githubusercontent.com/45850524/50482594-633a3380-09b5-11e9-8fb5-832c7ae9ab25.jpg)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/51704444-144ce180-1fe7-11e9-8de6-ec07df883f06.png)
