### ISSUE TITLE
Foreign Entity type showing prior to country

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#204]
The foreign entity type is being listed prior to me selecting the country.  The foreign entity type is based on the country selection.

![2018-12-27_9-19-22](https://user-images.githubusercontent.com/45850524/50483223-c4afd180-09b8-11e9-89eb-1dcb8fc20abd.jpg)

**Comment by dutchTender** [comment]
this page have been reworked as well. will check this in the latest build.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/51493820-85d92580-1d84-11e9-814a-24f260f9099b.png)

![image](https://user-images.githubusercontent.com/44168600/51493831-8d98ca00-1d84-11e9-9dac-ddc2e0013a76.png)
