### ISSUE TITLE
Add Additional Phone Number throws random error

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#207]
When clicking "add additional phone number" on the owner page, I get an error on the top of the page:

![home1](https://user-images.githubusercontent.com/45850524/50483719-fe81d780-09ba-11e9-8467-dd48fcf6f9ca.jpg)

**Comment by JackieBabos** [comment]
As of 2/13 this is no longer an issue since the add additional button isn't there currently. But will come back, and reopen the issue if necessary, to this to make sure this isn't an issue when we add the buttons back in.
