### ISSUE TITLE
Add additional name text is not aligned

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#208]
The text is not aligned with the rest of the fields and it is bold.

![2018-12-27_9-19-22](https://user-images.githubusercontent.com/45850524/50484053-81eff880-09bc-11e9-9683-97e42cc912d7.jpg)

**Comment by dutchTender** [comment]
this page have been reworked. will check in the current version.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/50925096-50951500-141f-11e9-9978-881aa36a70e1.png)
