### ISSUE TITLE
Owner phone number

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#209]
1. The phone type dropdown is too small and doesn't accommodate the text.
2. I am not able to select the phone type.
3. The Ext. label is not aligned with the text box.

![2018-12-27_9-49-11](https://user-images.githubusercontent.com/45850524/50484127-ef9c2480-09bc-11e9-8862-d15766f04c0d.jpg)

**Comment by dutchTender** [comment]
@keytie I will update our data model to include phone number type and extensions.  I will also make sure Lynn align this up in our UI rework.

**Comment by dutchTender** [comment]
@keytie the phone number input on owner forms have been reworked.
![image](https://user-images.githubusercontent.com/7011252/50732115-e7bd4c80-1141-11e9-9623-d61b54d0f6fe.png)
