### ISSUE TITLE
When selecting "No" to attorney there shouldn't be a review page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#220]
After I select "No"
![image](https://user-images.githubusercontent.com/44168600/50641924-8a55af80-0f37-11e9-98d1-452728382912.png)

This page should not appear, since they don't have an attorney. 
![image](https://user-images.githubusercontent.com/44168600/50641943-9e011600-0f37-11e9-8a76-c961477a3f66.png)

**Comment by dutchTender** [comment]
i think this is no longer issue with validation working on these pages. but will test and verify and attempt to submit some empty forms or forms with required fields missing or duplicate emails in the application already.

**Comment by JackieBabos** [comment]
I think its no longer an issue as well. I receive validations now for missing fields.
