### ISSUE TITLE
Suffix on Attorney

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#227]
Need to have the roman numerals and suffix.

Needs to be:

![image](https://user-images.githubusercontent.com/44168600/50775023-0ff09c80-1263-11e9-9a01-23e68a4a347c.png)

Currently:
![image](https://user-images.githubusercontent.com/44168600/50774975-e9cafc80-1262-11e9-99a3-8dab71244f83.png)

**Comment by dutchTender** [comment]
I think i fixed this. let me know what page this is on.
