### ISSUE TITLE
Consent Template

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#228]
Use the following document to use as the "Consent Template". This one only for name right now.

**Comment by JackieBabos** [comment]
"If the system could be dynamic enough to where the template would be populated with the right language based on how the user answers the name/portrait/consent section of the application.  That way, only one template would be needed as opposed to three." - Al

**Comment by dutchTender** [comment]
i think this is doable, but probably an enhancement.

**Comment by JackieBabos** [comment]
Update: Change the document to be for portrait. Document is below. 
[Consent_template_Portrait.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/2890570/Consent_template_Portrait.docx)

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/54305368-8f6d5580-459d-11e9-8cd2-556eedecce20.png)

**Comment by JackieBabos** [comment]
@nguyenvivi For this one would you just like for us to switch out the document from 'name" to "portrait or likeness" for the scenario high priority, or would you like us to spend the time trying to figure out how to dynamically change the templates for the user? If you just want to have us switch out the documents, we can create another issue for the enhancement of dynamically changing the word documents for us to look at later.  

Let me know which one you would like for us to do. Thanks!

**Comment by nguyenvivi** [comment]
Yes, please go with "portrait or likeness" for now.  Please add another issue to cover the enhancement of dynamically changing the word document later.  Thanks!

**Comment by JackieBabos** [comment]
Split this issue, and created issue #447 for the dynamic loading consent template. 

All to be done with this issue now is to change the document we have in the prototype with the attached document. 
[Consent_template_Portrait.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3013582/Consent_template_Portrait.docx)
