### ISSUE TITLE
Attorney Information save notification

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#235]
Remove “.” after “…Information…”.  It should say “Attorney Information has been saved.”

![image](https://user-images.githubusercontent.com/44168600/50927797-dcf70600-1426-11e9-80bd-e0472de8e95b.png)

**Comment by dutchTender** [comment]
all periods have been removed from auto save messages

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/50973155-38240980-14b6-11e9-836b-2ec3e8af22f1.png)
