### ISSUE TITLE
Required key should only be shown when fields are required 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#239]
“*=Required” should only be displayed on the screen that has required data fields.

![image](https://user-images.githubusercontent.com/44168600/50928401-91455c00-1428-11e9-9fe2-a9400e93b16e.png)

**Comment by JackieBabos** [comment]
***Need to talk to the BAs about this. The user needs to click on US or Foreign Entity to have the owner information pop up so its needed, so should that be required?

**Comment by dutchTender** [comment]
probably not, i think it forces the user the select something to move
forward. it is just that we don't ahve foreign entities right now. i will
remove this for the demo tommrow

**Comment by dutchTender** [comment]
I will remove this.
