### ISSUE TITLE
Additional Name

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#240]
We have two different layouts for additional name. Need to select one method all across all entity types.
If we do with the second picture, there needs to be a data field for the user to provide the additional name.

1)
![image](https://user-images.githubusercontent.com/44168600/50928824-b6869a00-1429-11e9-8f08-dd3f53c08085.png)

2)
![image](https://user-images.githubusercontent.com/44168600/50928857-cef6b480-1429-11e9-868d-db6598db737c.png)

**Comment by dutchTender** [comment]
let me check the base html .....this might be lynn

**Comment by dutchTender** [comment]
l will see if i can make this change after I finish the filing basis java
script file upload
