### ISSUE TITLE
Add additional General Partners

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#241]
When “Partnership” is selected as Entity Type, user should be able to add additional partner(s) under “General Partners” Section.

![image](https://user-images.githubusercontent.com/44168600/50929052-4f1d1a00-142a-11e9-8388-865b62d03706.png)

**Comment by dutchTender** [comment]
will come back to this, this is quite complicated to do on the back end, i am sure front end is too.

**Comment by dutchTender** [comment]
@JackieBabos let me know if having multiple partners is in their scenarios. if it is, i will move this up the priority list

**Comment by JackieBabos** [comment]
Currently adding multiple partners is not in the scenario.

**Comment by JackieBabos** [comment]
Currently being worked on.
