### ISSUE TITLE
Validation - State where legally organized 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#242]
Required fields validation skips the “General Partners”, “State Where Legally Organized”.

![image](https://user-images.githubusercontent.com/44168600/50929171-986d6980-142a-11e9-842d-1d3e6dd3850e.png)

**Comment by JackieBabos** [comment]
*Need a better picture to show

**Comment by dutchTender** [comment]
found the issue. this is a problem with all state and country fields, where the default "select" has the value of "select", i tested on attorney, after changing it to empty string, validation occurs. I will update registration, user account, attorney forms and owner forms

**Comment by dutchTender** [comment]
this issue have been fixed and is deployed in stage and in demo server.
