### ISSUE TITLE
Remove duplicate informational text for mark type and hyperlink TMEP section

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#252]
Need to remove everything that is in the crossed out box. So delete everything that comes after “like tax preparation services”, since the remaining information is broken down in the individual information sections.

![image](https://user-images.githubusercontent.com/44168600/50974327-fcd70a00-14b8-11e9-8e13-d5f7df43d129.png)

**Comment by JackieBabos** [comment]
Hyperlink the “See TMEP Section 1306” with the link that is there.

![image](https://user-images.githubusercontent.com/44168600/50974475-4fb0c180-14b9-11e9-813a-0ee77e5b0679.png)

**Comment by JackieBabos** [comment]
Also make sure Lynns latest is on the server. Here it is displaying not the most up to date. 

![image](https://user-images.githubusercontent.com/44168600/50976034-f8145500-14bc-11e9-9508-dd33479e2a96.png)

**Comment by JackieBabos** [comment]
Need to integrate lynns latest page: mark_layout_M017

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53174607-3753bc80-35b8-11e9-8169-d1dc93a42db5.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53174934-e85a5700-35b8-11e9-8477-0795cbb5396d.png)
