### ISSUE TITLE
Progress Bar issues

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#255]
1.	When user comes back to an application in draft, the system does not take user back to where he/she left off.  
2.	The Breadcrumbs/Progress Bar does not work properly.  In this scenario, user left off during trademark details, the breadcrumbs did not show that the trademark details information is in progress when the user logged back in. 

![image](https://user-images.githubusercontent.com/44168600/50975024-863b0c00-14ba-11e9-9156-1ff58283731d.png)

**Comment by dutchTender** [comment]
this feature is not fully implemented yet.
