### ISSUE TITLE
Confirm Primary Attorney

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#257]
When a primary attorney selection is changed, it’s not clear that the user needs to select “Confirm Primary Attorney” to make the change before proceeding to the next screen.

![image](https://user-images.githubusercontent.com/44168600/50975658-20e81a80-14bc-11e9-8ea2-9f819fa0ad3e.png)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/52656762-03e0a600-2ec5-11e9-84ce-bd049d1425bb.png)


![image](https://user-images.githubusercontent.com/44168600/52656714-eb708b80-2ec4-11e9-8926-ddb131a72c40.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53185248-a3d8b680-35cc-11e9-9850-5c4bcd2d4617.png)
added 5 second of high light affects on attorney primary set and page load for primary attorney

**Comment by dutchTender** [comment]
also the primary attorney will always be first in the list on a page reload.

**Comment by nguyenvivi** [comment]
This is not complete.  Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/46028434/53421589-e4a94480-39ab-11e9-9a4f-5c927f90cce1.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53495928-f7388200-3a6e-11e9-828c-f5da2b014602.png)
