### ISSUE TITLE
Name/Portrait/Signature Options

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#263]
Name/Portrait/Signature needs to have some of the options removed on some of the marks. 

For Standard Character: Only NAME should be an option. 
![image](https://user-images.githubusercontent.com/44168600/50984155-27cc5880-14cf-11e9-8d78-657372d653b5.png)

For Stylized: NAME and SIGNATURE should be the only options
![image](https://user-images.githubusercontent.com/44168600/50984250-6b26c700-14cf-11e9-89d0-5a85f4defa70.png)

For Design Only: Only PORTRAIT should be the option.
![image](https://user-images.githubusercontent.com/44168600/50984349-b17c2600-14cf-11e9-98a1-035817541f99.png)

**Comment by dutchTender** [comment]
This is definitely do able. Since we tracking mark types. I can simply out
put the correct html block.

**Comment by dutchTender** [comment]
stylized
![image](https://user-images.githubusercontent.com/7011252/53173357-80eed800-35b5-11e9-9b07-e9735eca64f3.png)
