### ISSUE TITLE
Concurrent Use - TTAB

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#267]
When the user selects "Prior decision made by the Trademark Trial and Appeal Board (TTAB)"

A "Provide TTAB Proceeding Number" input box should appear. 

![image](https://user-images.githubusercontent.com/44168600/51197507-c0901900-18bf-11e9-93d9-ab10b3c9ab89.png)

**Comment by dutchTender** [comment]
I checked the static html. this is in that version as well.

**Comment by JackieBabos** [comment]
Lynn completed, located on file 'Additional_Information'

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52502584-2450ed80-2bb1-11e9-8b33-d7a672e20e81.png)
