### ISSUE TITLE
Not Applicable functionality 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#270]
1.	If “Not applicable” is selected, users should be able to select Pending Foreign Application or Foreign Registration.  Currently users cannot select the other options unless they deselect “Not Applicable”.  

Is it possible to change the behavior so that if user selects Pending Foreign Application, “Not Applicable” selection will be automatically deselected?

2.	If there is only ONE goods/service was selected, the system should not display the option for “Not Applicable” because user already selected “Yes” to indicate that he/she has a pending Foreign Application and/or a Foreign Registration.

![image](https://user-images.githubusercontent.com/44168600/51199774-b6711900-18c5-11e9-8ae9-ab4c04fc274c.png)

**Comment by dutchTender** [comment]
we need to walk lynn trough this behavior. she implemented these check box
behaviors

**Comment by dutchTender** [comment]
I believe lynn have updated this issue. I will need to integrate it into the application.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56472812-690ac780-6431-11e9-8e71-3b7a5fb7cd3d.png)
when only one good and service for a class
