### ISSUE TITLE
Mark type question

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#282]
Remove the required “*” for the Uncommon Mark Types. The orange highlight. 

![image](https://user-images.githubusercontent.com/44168600/53042048-68ff4300-3453-11e9-9709-efef0947faf2.png)

**Comment by JackieBabos** [comment]
Trademark/Servicemark should be selected by default.

![image](https://user-images.githubusercontent.com/44168600/52229403-d2435b80-2882-11e9-915f-85f6abc53f99.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53108158-850eed00-3504-11e9-97fb-8902f85ba863.png)

**Comment by nguyenvivi** [comment]
Testing was conducted on version 1.0.0

![image](https://user-images.githubusercontent.com/46028434/53428549-fd6c2700-39b8-11e9-927b-3e41e94e07f5.png)

**Comment by JackieBabos** [comment]
Agree with Vi, the asterisk is there again. So that needs to be removed.

**Comment by l-stanny** [comment]
removed asterisk @JackieBabos @serra-trinh this is in GitHub ready for integration

**Comment by JackieBabos** [comment]
Closing this issue due to the fact this is the same issue as #425 and that was closed.
