### ISSUE TITLE
"The mark consists of" not overridden

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#283]
"This mark consists of" should be there at all times, and not disappear when the user starts to type. 

![image](https://user-images.githubusercontent.com/44168600/51495433-41508880-1d8a-11e9-986f-7656de611598.png)

Needs to be like this
![image](https://user-images.githubusercontent.com/44168600/51495483-8379ca00-1d8a-11e9-8b48-e90cb383445c.png)

**Comment by dutchTender** [comment]
this also a front end feature that lynn needs to build

**Comment by JackieBabos** [comment]
@dutchTender this is in marks_design_with_text_uploaded_m5

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52589202-48f4d180-2e0c-11e9-8376-84817f1a52d9.png)
