### ISSUE TITLE
Header hover (mark and fee widget)

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#285]
When you hover over the fee widget it outlines the area.
![image](https://user-images.githubusercontent.com/44168600/51497153-33056b00-1d90-11e9-9e96-1c593cf2fed6.png)

When you hover over the mark image it changes the color of the text. Can the mark image hover match the fee widget?
![image](https://user-images.githubusercontent.com/44168600/51497191-59c3a180-1d90-11e9-9d88-f2370b87b79d.png)

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/52299516-988e5580-2953-11e9-860f-2d9b1ab57b59.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52502601-316ddc80-2bb1-11e9-8478-d42f26c5ba55.png)
