### ISSUE TITLE
Specimen thumbnail

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#289]
Please ensure that after the specimen image is uploaded, it will be displayed as a thumbnail.
![image](https://user-images.githubusercontent.com/44168600/51613621-d9b54d00-1ef1-11e9-935b-5bfde8c6d131.png)

**Comment by dutchTender** [comment]
we need to mock this up, i am not sure how that would fit with the upload button that span across the page

**Comment by dutchTender** [comment]
updated in the latest stage build.
