### ISSUE TITLE
One option to upload file

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#292]
We should present only one option to upload the file to the user.  

We should provide a capability to remove the uploaded file

![image](https://user-images.githubusercontent.com/44168600/51616902-1b95c180-1ef9-11e9-8cfe-232dac1540e6.png)

**Comment by JackieBabos** [comment]
Noticed this for Miscellaneous Info as well.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53170627-944a7500-35ae-11e9-9a58-04f9875cef62.png) fixed this and for misc info upload

**Comment by nguyenvivi** [comment]
completed.
