### ISSUE TITLE
Payment Screen Details are Accurate, But Need to Be Rearranged

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#294]
![capture](https://user-images.githubusercontent.com/34866507/51618174-ca3b0180-1efb-11e9-928b-fb7046652b29.JPG)

The fees are accurate but they should be on different lines separated by the fee codes. Right now we have:

Fee Code-Item Price- Qty Fee Code-Item Price- Qty

It should be displayed as 

Fee Code-Item Price- Qty
Fee Code-Item Price- Qty

**Comment by dutchTender** [comment]
gonna need @l-stanny  to mock this up. i basically just copied her base html.
