### ISSUE TITLE
Principal Register

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#295]
Remove the “Edit” function.

Replace “You are seeking registration on the Principal Register” with the following:

“You are seeking registration on the:
•	Principal Register
o	Supplemental Register
”

Please note that the Principal Register option is selected by default.
Issue #284 

![image](https://user-images.githubusercontent.com/44168600/51618709-c22f9180-1efc-11e9-8da2-9f686a09e2a9.png)

**Comment by JackieBabos** [comment]
Updated in UXPin: https://preview.uxpin.com/646c2ecbcfb400369217dd7cdd69a4ab19148f3f#/pages/88480393/simulate/sitemap?mode=i

![image](https://user-images.githubusercontent.com/44168600/51618776-e25f5080-1efc-11e9-9880-c060617d8ba6.png)

**Comment by l-stanny** [comment]
Completed. 
![screen shot 2019-02-08 at 7 04 06 pm](https://user-images.githubusercontent.com/8275852/52512723-6fc8c300-2bd4-11e9-9998-3f0da1ea4af9.png)
