### ISSUE TITLE
2f Informational Text

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#296]
Informational text for 2f claim is missing. Insert the following.

A mark that is widely used by others is not distinctive. A trademark on the Principal Register must be distinctive enough to unambiguously identify the mark owner as the source of the goods or services provided under the mark. If a mark is not inherently distinctive because the wording is descriptive, geographically descriptive, or a surname, the mark owner must show that the mark has acquired distinctiveness through evidence, ownership of a same/similar mark on the Principal Register, or five years’ use.

![image](https://user-images.githubusercontent.com/44168600/51620006-7f22ed80-1eff-11e9-8d93-800f7e8cc418.png)

**Comment by dutchTender** [comment]
issue resolved and updated git hub. caused by the html that lynn turned over had duplicate ids. I will actively test her html before integrating going forward.

**Comment by dutchTender** [comment]
this will actually hide the 2f check box as they had the same id.
