### ISSUE TITLE
Upload Capability does not work 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#298]
Upload does not work for Concurrent Use and 2(f) claim.

![image](https://user-images.githubusercontent.com/44168600/51621556-c78fda80-1f02-11e9-9b0d-57186b0551fe.png)

![image](https://user-images.githubusercontent.com/44168600/51621608-e7bf9980-1f02-11e9-9642-aff3ded85fe4.png)

**Comment by dutchTender** [comment]
updated style on this. will implement functionality next

**Comment by dutchTender** [comment]
I will be doing this today as well if lynn html is not here today

**Comment by dutchTender** [comment]
I will get this started today

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53170020-face9380-35ac-11e9-8b3b-ae58feb9fd5b.png)
concurrent use supporting document upload

**Comment by dutchTender** [comment]
the third row of radio buttons   which reads "what is your claim based on"? is related to the first question "Are you claiming that your mark is inherently distinctive". it is not related if the claim is on whole or in part. if you interpret the current behavior, which have whole drives the evidience of support, and part just drives the location of the part input. it would be saying that if you claim part, then you do not need to provide evidence for distinctiveness

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53202559-d696a500-35f4-11e9-8627-d5b1b2079e8d.png)

file upload and the path leading to it implemented with auto save and persistence behavior. still need to do the same for prior registration and five year of use

**Comment by dutchTender** [comment]
completed auto save for all fields under 2f claim. all radio check boxes and inputs.

**Comment by nguyenvivi** [comment]
Testing was conducted on version 1.0.0.

This issue has not been addressed yet.  User still can't upload a DOCUMENT.

**Comment by JackieBabos** [comment]
@dutchTender A file upload needs to happen on this upload.

**Comment by dutchTender** [comment]
I can upload on the BA server and the stage server.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53577835-5ddb9f80-3b44-11e9-8ee5-498dce334dcc.png)

this works. please test again.

**Comment by l-stanny** [comment]
> Upload does not work for Concurrent Use and 2(f) claim.
> 
> ![image](https://user-images.githubusercontent.com/44168600/51621556-c78fda80-1f02-11e9-9b0d-57186b0551fe.png)
> 
> ![image](https://user-images.githubusercontent.com/44168600/51621608-e7bf9980-1f02-11e9-9642-aff3ded85fe4.png)

@dutchTender Component has been updated and tested locally, committed

**Comment by l-stanny** [comment]
> Upload does not work for Concurrent Use and 2(f) claim.
> 
> ![image](https://user-images.githubusercontent.com/44168600/51621556-c78fda80-1f02-11e9-9b0d-57186b0551fe.png)
> 
> ![image](https://user-images.githubusercontent.com/44168600/51621608-e7bf9980-1f02-11e9-9642-aff3ded85fe4.png)

@dutchTender @JackieBabos Component has been updated and tested locally, committed
