### ISSUE TITLE
Declarations

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#306]
We will need to have the declarations be populated correctly based on the scenarios/filing basis. The declarations are in the word document that is attached. I can walk you through this when you get to this point. 

![image](https://user-images.githubusercontent.com/44168600/51688746-3e8ca800-1fc3-11e9-906b-bdcfff3568e6.png)
[Declarations for Prototype.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/2792394/Declarations.for.Prototype.docx)

**Comment by dutchTender** [comment]
I will work on this next while waiting on lynn turning over grid view 
and or TEAS field validatoin toggle

**Comment by dutchTender** [comment]
added functionality to additional info, concurrent use evidence file upload. once this is done. the evidence check box will be checked automatically.
