### ISSUE TITLE
Declaration "check all"

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#307]
In addition to placing a check box next to each statement,  there should also be a “check all”, option at the top so the user would only have to click once.

![image](https://user-images.githubusercontent.com/44168600/51689900-95937c80-1fc5-11e9-8d16-db1ec0b36158.png)

**Comment by dutchTender** [comment]
not sure where to put the check all box. i feel like it should not be aligned with the existing check boxes.
also need specific language here.

1. get the language from the BAs
2. have @l-stanny add a check box here with the language supplied by the BAs
