### ISSUE TITLE
Change to U.S. Entity

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#317]
Please change “US Entity” to “U.S. Entity”.

![image](https://user-images.githubusercontent.com/44168600/52003186-db52b800-2491-11e9-98e8-f51320da0b86.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53046647-8259bc80-345e-11e9-890c-8bacc9fe9a47.png)
