### ISSUE TITLE
Update text "Last Name field"

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#318]
Please change the higlighted text in the informational message to “Last Name field” for consistency.

![image](https://user-images.githubusercontent.com/44168600/52005015-a4cb6c00-2496-11e9-9d45-9fdbef349db4.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53107869-fc904c80-3503-11e9-8dcb-657d7e6963c4.png)

**Comment by nguyenvivi** [comment]
Complete.
