### ISSUE TITLE
Update wording/style on Review Application

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#319]
1.	Please replace “Identification” with “Filing Basis”.
2.	Please replace “Description” with “Identification”.

![image](https://user-images.githubusercontent.com/44168600/52007816-4f468d80-249d-11e9-9042-99d982e8b4b1.png)

1.	Please use bold font for the orange highlighted text.
2.	Please do not use bold font for the yellow highlighted text.

![image](https://user-images.githubusercontent.com/44168600/52007829-5b324f80-249d-11e9-8ad1-f3ab778e178b.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53046507-33ac2280-345e-11e9-80fa-402fae3913b3.png)
