### ISSUE TITLE
Remove text under Concurrent Use

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#320]
Please remove the highlighted text under Concurrent Use.  It already appears on the top of the Rare/Uncommon Situations.

![image](https://user-images.githubusercontent.com/44168600/52007943-93399280-249d-11e9-8b3f-5be7e76f1016.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53046192-80dbc480-345d-11e9-9923-149407e1fe5b.png)
