### ISSUE TITLE
Filing Basis - Text change

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#323]
Replace the highlighted text with “Provide a specimen for the goods/services within this class.  Only one specimen is required per class.”

![image](https://user-images.githubusercontent.com/44168600/52013440-0e557580-24ab-11e9-86f1-5c3a400afdf9.png)

Update the language to “Are you currently using the mark in commerce for this good/service?”
![image](https://user-images.githubusercontent.com/44168600/52225025-71625600-2877-11e9-8851-33f4e908c64d.png)

**Comment by dutchTender** [comment]
@dutchTender

**Comment by JackieBabos** [comment]
1. Update the language to “Are you currently using the mark in commerce for this good/service?”

**Comment by JackieBabos** [comment]
No longer applicable due to issues #341 and #

**Comment by JackieBabos** [comment]
This will only appear when the user says "yes" to the Is the mark currently on use on the previous page.

**Comment by dutchTender** [comment]
this seems to be an out dated requirement. please reference #371.
