### ISSUE TITLE
Additional Name Update

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#325]
1.	Please change the highlighted text to “Add additional name if Owner is doing business as or trading under a different name.”

2.	Replace “type” with the text above.

3.	Once user selects one of the items from the dropdown list, the “Name” field will be displayed.

![image](https://user-images.githubusercontent.com/44168600/52018481-92622a00-24b8-11e9-972a-395d99a61f5c.png)

https://preview.uxpin.com/646c2ecbcfb400369217dd7cdd69a4ab19148f3f#/pages/87302081/simulate/sitemap?mode=i

**Comment by JackieBabos** [comment]
Edit text to:
"Add additional name if Owner is doing business as or trading under a different name"

Once user selects one of the items from the "Add additional name" dropdown list, the “Name” field will be displayed.

Part of Issue #325 that was closed.

![image](https://user-images.githubusercontent.com/44168600/52724461-5da4a700-2f7d-11e9-9eef-69def5ca489b.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53372399-c34f4680-3920-11e9-8e6a-01271249caca.png)
added this feature for all owner forms and owner edit forms

**Comment by nguyenvivi** [comment]
Please see the attached screenshot.

![image](https://user-images.githubusercontent.com/46028434/53422344-4ae29700-39ad-11e9-891c-b7bb3d3ce130.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56742673-2f90cf80-6743-11e9-84ce-d7d0ebe9708a.png)
need java script on edit page to show field.
