### ISSUE TITLE
Dashboard headings

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#327]
Please make the widget heading (as   highlighted) more prominent.       

Please make the following edits:   
1.       Change “Upcoming Action Due” to “Upcoming Action(s)   Due”   
2.       Move the “New Application” button to the side so the   widget heading can be centered.

![image](https://user-images.githubusercontent.com/44168600/52061918-7ce31380-253d-11e9-83c4-161f328d2306.png)

**Comment by dutchTender** [comment]
i would leave this for lynn

**Comment by dutchTender** [comment]
@l-stanny

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/53042758-ff803400-3454-11e9-9499-4c275b852add.png)

**Comment by l-stanny** [comment]
@JackieBabos @serra-trinh 'Upcoming Action Due' edited to 'Upcoming Action(s) Due' and pushed to GitHub, assigning to @dutchTender
