### ISSUE TITLE
"Mark Description" not system required

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#328]
“Mark Description” field is not a   required data for TEAS regular.  This   field is required for TEAS Plus only.
Remove the asterisk. 

![image](https://user-images.githubusercontent.com/44168600/52062260-2fb37180-253e-11e9-9a7c-da542c8aac99.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52063183-17dced00-2540-11e9-9744-e7bac520aed5.png)

**Comment by dutchTender** [comment]
this have been updated and should be reflected in the stage server.

**Comment by dutchTender** [comment]
this is still on the b&w claim. let me update it
