### ISSUE TITLE
Supplemental Register Fee change

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#331]
Once issue #295 is completed.

When a user changes to “Supplemental Register”, the following things would happen:
1.	The following warning should be displayed: “Applications on the Supplemental Register do not qualify for the lowest filing fee per class.”
2.	The fee widget will be updated with the highest fee per class.

![image](https://user-images.githubusercontent.com/44168600/52064590-f0d3ea80-2542-11e9-868c-2fcad8eccec8.png)

**Comment by dutchTender** [comment]
@l-stanny  need you to design where this new message should appear

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53045933-d95e9200-345c-11e9-85dc-3c52fa145e7a.png)
showing currently default register type with qualifying lowest fee

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53045972-f004e900-345c-11e9-9a42-0e26be76393e.png)
fee updated and warning message posted after switching to supplemental register
