### ISSUE TITLE
Correspondent Information - Attorney 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#332]
Corespondent Information Section:
In this scenario, we have an appointed Attorney, therefore the following data should be displayed.
1.	“Owner” should be replaced with “Name”
2.	Email address
3.	Address (display the entire address with multiple lines)
4.	Phone Number

For example:
![image](https://user-images.githubusercontent.com/44168600/52065873-65a82400-2545-11e9-8be1-59755165b4b4.png)

![image](https://user-images.githubusercontent.com/44168600/52065877-693bab00-2545-11e9-8e53-ff19a67f6432.png)

**Comment by dutchTender** [comment]
@dutchTender

**Comment by dutchTender** [comment]
I will update this next

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53169893-96133900-35ac-11e9-94a1-4879a4ed12b5.png)

**Comment by nguyenvivi** [comment]
Please see the screenshot below.

![image](https://user-images.githubusercontent.com/46028434/53507560-1ee71480-3a86-11e9-91ad-efa8b7cea0df.png)

**Comment by nguyenvivi** [comment]
Please note that this need to be fixed for Foreign Application as well.

**Comment by dutchTender** [comment]
@nguyenvivi how does this look?

![image](https://user-images.githubusercontent.com/7011252/54706236-c51dbb80-4b14-11e9-9d0b-aba0905522bb.png)
