### ISSUE TITLE
Owner Information - Editable 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#334]
When user selects “Edit” from the Review and Edit page in the Owner Information, the Owner information is not editable.

Place an edit button next to the owner name, and when the user clicks 'Edit' it prepopulates their information into the text fields for the user to edit. 

![image](https://user-images.githubusercontent.com/44168600/52077231-7dd86d00-255e-11e9-9893-0c5d8bb7de7b.png)

**Comment by dutchTender** [comment]
one thing to think about. how should the user return back to the owner
review. do we need a done button? there should not be a next or previous
when in this context.

**Comment by JackieBabos** [comment]
Yeah a done button makes sense. would this done button appear all of the time, or only when the user clicks edit on the owner information review page, and then button displays.

**Comment by dutchTender** [comment]
@dutchTender @l-stanny (we both have work on this one)

**Comment by dutchTender** [comment]
this is done for owner indiviudal

**Comment by dutchTender** [comment]
we have implemented this feature for u.s individual and attorney. we will add the rest of the owner forms by the end of next week.

**Comment by dutchTender** [comment]
probably should move this up in priority

**Comment by JackieBabos** [comment]
Latest BA Comment: 
When we go back to edit the owner information, the previously entered data for Owner Name information was missing.

**Comment by dutchTender** [comment]
@JackieBabos this will be fixed once we add the other owner edit forms. this happens when you create an owner that is not individual, like corp or partner, and the edit button takes them to the owner individual edit form

**Comment by dutchTender** [comment]
making a look and feel update. currently looks like this

![image](https://user-images.githubusercontent.com/7011252/53255222-317ed980-3693-11e9-8a87-f03e9559f9bd.png)

**Comment by dutchTender** [comment]
updated version
![image](https://user-images.githubusercontent.com/7011252/53255252-422f4f80-3693-11e9-93d7-5a5f3e1f90a1.png)

**Comment by dutchTender** [comment]
to be consistent, as the attorney edit page looks like this 
![image](https://user-images.githubusercontent.com/7011252/53255317-612de180-3693-11e9-8ab4-ce83f32e6391.png)

**Comment by dutchTender** [comment]
will need to removed the form fill buttons from attorney edit page.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53265059-38194b00-36ab-11e9-9859-8346162f54ba.png)
added the ability to set the form based on owner type. here is a example of owner u.s corporation page. this is probably why the client was not seeing their entries on the edit page before. so once this is complete. that issue should also be resolved.
