### ISSUE TITLE
2 Good/Service per class radio buttons malfuctioning 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#337]
If you select multiple good or services per class. Only the first radio button set is displaying information. And the radio button that you select on the 2nd good/service displays on the 1st set of radio buttons. 

![image](https://user-images.githubusercontent.com/44168600/52135647-40361b80-2614-11e9-8b29-50c23635e024.png)
 
When I click yes to "gears for machines", the radio button for 'agricultural implements' switches to yes. 
![image](https://user-images.githubusercontent.com/44168600/52135840-bd619080-2614-11e9-81db-b62c86b6a310.png)

**Comment by dutchTender** [comment]
ok, l will work on this next, before the teas review page merge
