### ISSUE TITLE
Warning for Color - removed

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#340]
Since we are not using Artificial Intelligence Technology, in this scenario, the Mark is in black and white.  Please remove the highlighted text and the checkbox.

![image](https://user-images.githubusercontent.com/44168600/52294413-4b0beb80-2947-11e9-964b-c0fcd0b546d5.png)

**Comment by dutchTender** [comment]
I will get this one

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53045785-7bca4580-345c-11e9-9005-65e500875e2b.png)
