### ISSUE TITLE
Gray out signature options

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#342]
Please gray out all of the signature options besides "Sign Directly"

![image](https://user-images.githubusercontent.com/44168600/52303928-684cb400-295f-11e9-947e-8df626096269.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53045601-0fe7dd00-345c-11e9-93f8-79bdab038e59.png)
