### ISSUE TITLE
Specimen - Reduce Fee 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#344]
If the mark is in use for a good/service, a specimen is required for TEAS Plus.  User should not have to select “check here to provide a specimen…” to be able to update a specimen.

![image](https://user-images.githubusercontent.com/44168600/52362399-7e657d80-2a0e-11e9-8c11-076adf8693ee.png)

The highlighted text is a required data field for TEAS Plus.
![image](https://user-images.githubusercontent.com/44168600/52362421-84f3f500-2a0e-11e9-95a8-4f1948f28967.png)

**Comment by dutchTender** [comment]
so where should the label go? its for the specimen, not for the check box. and seems like you want that the check box always there and checked. then do we even need it there?

**Comment by dutchTender** [comment]
i ll put the label next to the text for file uploader

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53168653-2b143300-35a9-11e9-9b72-89845818195f.png)
