### ISSUE TITLE
Hello world displaying on review page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#347]
Not sure why “Hello world” is showing in the Mark image section of the review page.

![image](https://user-images.githubusercontent.com/44168600/52418541-44eb4b80-2abc-11e9-83c7-8549d7d90584.png)

**Comment by dutchTender** [comment]
this the behavior for standard characters

**Comment by dutchTender** [comment]
let me try to recreate this
