### ISSUE TITLE
Remove “Candy” from “Foreign Registration Certificate” 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#349]
Please remove “Candy” from “Foreign Registration Certificate” 

![image](https://user-images.githubusercontent.com/44168600/52418885-fd18f400-2abc-11e9-8a6d-9392b12a1c5a.png)

**Comment by JackieBabos** [comment]
Reorder - "Foreign Registration Certificate - Candy"

**Comment by dutchTender** [comment]
ok, will do. I will complete this and then push an update to stage
