### ISSUE TITLE
'Signature' and info text

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#351]
1.	Replace “Sign” with “Signature”
2.	Please provide the following informational text for Signature: “To electronically sign the application enter any combination of alpha numeric characters between two forward slash symbols (/); e.g., /jane smith/, /rdr/, or /127/).”

![image](https://user-images.githubusercontent.com/44168600/52422241-ad89f680-2ac3-11e9-99f8-f4c7186a37d4.png)

**Comment by dutchTender** [comment]
I can probably get this one too
