### ISSUE TITLE
Dashboard data 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#352]
The highlighted upcoming section should be changed to “File Petition”
![image](https://user-images.githubusercontent.com/44168600/52422301-cb575b80-2ac3-11e9-9dd0-f8aa14b73693.png)

Once the application is filed and submitted, status should be displayed as “Submitted”.
![image](https://user-images.githubusercontent.com/44168600/52422315-d1e5d300-2ac3-11e9-9f73-b9653474f709.png)

**Comment by dutchTender** [comment]
let me know if this can be close.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/52645921-c02f7180-2eaf-11e9-8ba9-b9fa1a77880c.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos assigning to @dutchTender Link change from 'File a Petition to Revive' to 'Submitted' needs to happen server-side. The link, 'File a Petition to Revive', is in place in GitHub.
