### ISSUE TITLE
remove "foreign" from entity type

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#355]
Please remove “Foreign”.  Entity type should be “Corporation” only.  

![image](https://user-images.githubusercontent.com/44168600/52440099-42ecb100-2aeb-11e9-9e45-d2dad2f4faeb.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52590927-94a97a00-2e10-11e9-8665-9627cd02f491.png)
