### ISSUE TITLE
remove 1(b) language in review

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#358]
Since this is a 1(b) filing basis, please remove the highlighted text as it’s not applicable.

![image](https://user-images.githubusercontent.com/44168600/52441949-03749380-2af0-11e9-8fc5-a8a931a8c1e8.png)

**Comment by dutchTender** [comment]
please let me know if this maybe close.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/52647223-4f3d8900-2eb2-11e9-8f60-107f850cc493.png)
