### ISSUE TITLE
declarations missing checkboxes

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#359]
1.	The system should present the highlighted text in a separate check box.
2.	Missing the Control of Commerce Statement for 1(b): “The applicant has a bona fide intention to use the mark in commerce on or in connection with the goods/services in the application; and”
 
(This scenario is 1a and 1b)

![image](https://user-images.githubusercontent.com/44168600/52442104-59493b80-2af0-11e9-8e94-43c8e1b6c7ce.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52580423-49826d80-2df6-11e9-9d00-3c5f1efda5d0.png)
