### ISSUE TITLE
foreign application filing date

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#360]
The “Foreign application filing date” as highlighted should be within 6 months of today’s date (2/6/2019).  If the user provides a date that is not within 6 months of today’s date, the system shall display an error message: “You cannot claim Section 44(d) priority, because your attempted U.S. filing is outside the 6-month window. (i.e., from when the foreign application was filed).”

![image](https://user-images.githubusercontent.com/44168600/52443861-d8d90980-2af4-11e9-932c-282042b51436.png)

**Comment by dutchTender** [comment]
it it possible we can just have an info text on this behavior and grey out any dates greater then 6 month

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52580483-6dde4a00-2df6-11e9-81c4-0a5ac1f427b0.png)
info text

**Comment by dutchTender** [comment]
greyed out future date of 6 month from today.


![image](https://user-images.githubusercontent.com/7011252/52580513-86e6fb00-2df6-11e9-8bd9-259ed6ae0fd5.png)

**Comment by dutchTender** [comment]
leaving this open, since the BA's might want changes to this.

**Comment by dutchTender** [comment]
added logic to prevent user to put in future dates of more then 6 month for foreign application date.

**Comment by nguyenvivi** [comment]
I think there is a misunderstanding of the business rules.  The system should prevent the user from entering a date more than 6 months prior to today's date.

For example, if today's date is 2/26/2019, the system should not allow the user to enter a date for the "foreign application filing date prior" to 8/26/18.

**Comment by dutchTender** [comment]
@nguyenvivi we updated the logic to prevent past 6 month input into the foreign application filing date field.

![image](https://user-images.githubusercontent.com/7011252/53591220-7e662280-3b61-11e9-82b1-0fa326a322cb.png)  ...this will be in V.1.0.1  deployment

**Comment by nguyenvivi** [comment]
Testing was conducted on version 1.0.0.  Is this the latest version? If so, should it be 1.0.1?

![image](https://user-images.githubusercontent.com/46028434/53743229-4ebc6080-3e68-11e9-9263-bfd4cb485d84.png)

**Comment by dutchTender** [comment]
I was able to replicate this on my end for manual entries. will start
looking into a resolution

**Comment by dutchTender** [comment]
still need java script to prevent user type in value

@l-stanny is this even possible?
