### ISSUE TITLE
Display Issue With New TEAS Plus Toggle Switch 

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#361]
The "n" in "On" is visible when the toggle is set to "Off." Issue does not exist in static HTML.

![image](https://user-images.githubusercontent.com/34866507/52586551-c832d700-2e05-11e9-9e2f-f05b1816c29a.png)

**Comment by dutchTender** [comment]
let me see if i can move the "on" text to the left 1 or 3 pixles

**Comment by dutchTender** [comment]
issue resolved.

![image](https://user-images.githubusercontent.com/7011252/52589718-80b04900-2e0d-11e9-8a03-71d6badfb508.png)
