### ISSUE TITLE
Grey Box Shown When Hovering Over Cancel Button in Attorney/Owner Review Screens 

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#362]
![image](https://user-images.githubusercontent.com/34866507/52586660-0a5c1880-2e06-11e9-9693-32d6e2016a8b.png)

**Comment by dutchTender** [comment]
removed hover effects

![image](https://user-images.githubusercontent.com/7011252/52590044-5ad77400-2e0e-11e9-8797-8788fc2223d6.png)

**Comment by dutchTender** [comment]
My method of re moving the hover affects actually disables the button.

**Comment by dutchTender** [comment]
changed buttons to spans. this issue is now resolved.
