### ISSUE TITLE
Checkmarks displayed on top of Text in Declarations Section

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#363]
![image](https://user-images.githubusercontent.com/34866507/52587615-658f0a80-2e08-11e9-9589-4546b81ed164.png)

**Comment by dutchTender** [comment]
this is what i see
![image](https://user-images.githubusercontent.com/7011252/52589439-cf111800-2e0c-11e9-8571-ddc33efa0103.png)

**Comment by JackieBabos** [comment]
Only happens when the reduce fee mode is on.

**Comment by dutchTender** [comment]
went back to lynn's original design. i could not make it work on each check box locally.
![image](https://user-images.githubusercontent.com/7011252/53117126-2eaba980-3518-11e9-8460-bb38364c0ae0.png)
