### ISSUE TITLE
Trademark/Servicemark should be selected by default.

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#364]
![image](https://user-images.githubusercontent.com/44168600/52646123-3207bb00-2eb0-11e9-9cbf-133afacaf336.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/52646677-2a94e180-2eb1-11e9-8ec9-c26a880d0b1b.png)
