### ISSUE TITLE
Specimen in the Review Page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#365]
Also, the specimen files that were being uploaded need to be displayed in the review page as well.  Currently TICRS, it’s being displayed via a link as shown in the example below.  If possible, we would like to have it displayed as a thumb nail in the review page.

![image](https://user-images.githubusercontent.com/44168600/52658167-638c8080-2ec8-11e9-8566-8e5a8bced4df.png)

**Comment by dutchTender** [comment]
uploaded speciemn at class level 
![image](https://user-images.githubusercontent.com/7011252/53044797-052c4880-345a-11e9-92f5-e551860f8e4f.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044816-137a6480-345a-11e9-9ec2-652909241f48.png)
 specimen is applied to each good and service and rendered both on the review page and the pdf filing reciept.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044873-36a51400-345a-11e9-8566-a9f5399ed673.png)
