### ISSUE TITLE
1 (b) review text

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#366]
Since this is a 1(b) filing basis, the system should display declaration languages for 1(b):

“Intent to Use: The applicant has a bona fide intention, and is entitled, to use the mark in commerce on or in connection with the identified goods/services. (15 U.S.C. Section 1051(b)).”

![image](https://user-images.githubusercontent.com/44168600/52661391-f0870800-2ecf-11e9-99e7-113c19b2a184.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044683-b41c5480-3459-11e9-99be-ec0572074765.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044723-c7c7bb00-3459-11e9-9db2-763e248adea9.png)
