### ISSUE TITLE
Filing Receipt Updates

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#367]
1.	“Mark”: should include the mark image/thumb nail.  
2.	“Mark Statement”: we don’t have this data field; Please replace this with “Mark Description”
3.	Color Mark data field.  
![image](https://user-images.githubusercontent.com/44168600/52663057-bfa8d200-2ed3-11e9-9090-e95660a26f37.png)

**Comment by JackieBabos** [comment]
[Filing Receipt in TICRS.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/2857415/Filing.Receipt.in.TICRS.docx)

Attached is a filing receipt example.

**Comment by dutchTender** [comment]
let me see if i can add the images to the pdf.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53043627-e11b3800-3456-11e9-8afd-22f448a83881.png)

**Comment by dutchTender** [comment]
also added image for specimen. example below is specimen uploaded at the class level

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53043677-fdb77000-3456-11e9-9ef6-f9532be951a1.png)
