### ISSUE TITLE
Serial Number on success page 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#368]
Can we have the serial number that is populated for the user (that is shown in the dashboard), placed where the '#####' are located. 

![image](https://user-images.githubusercontent.com/44168600/52666867-634ab000-2edd-11e9-9b10-de5fab3bf9f7.png)

**Comment by dutchTender** [comment]
will get this next

**Comment by dutchTender** [comment]
found an issue with standard character receipt while working on this. will fix that issue too

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53043461-808bfb00-3456-11e9-95f4-947ecce4d6bb.png)

**Comment by dutchTender** [comment]
also fixed issue where the is USPTO generated image was not correctly populated.
