### ISSUE TITLE
Remove "TEAs" from auto save notification

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#370]
![image](https://user-images.githubusercontent.com/44168600/52724849-1cf95d80-2f7e-11e9-906b-0063c39b759f.png)

**Comment by dutchTender** [comment]
i ll get this next

**Comment by dutchTender** [comment]
i ll put a screen shot up when this is done

**Comment by dutchTender** [comment]
changed this to reduced fee

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53041094-13c23200-3451-11e9-84b7-dc054731b385.png)
