### ISSUE TITLE
Filing Basis Question Update

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#371]
Update the questions to the below:

1. Are you currently using the mark in commerce for at least one of the good/services in this class?
2. Would you like to provide one specimen for all goods/services within this class?

The text, "Only one specimen is required per class." should appear when the specimen upload also appears. 

When the user says yes, to providing one specimen for the g/s in the class; have the "Click here to provide a specimen..." be grayed out. 

When the user says no, to currently using the mark in commerce, have the goods/services in that class be defaulted to "no".

**Comment by dutchTender** [comment]
I ll get this

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044199-5a675a80-3458-11e9-9949-a688afc47488.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53044211-62bf9580-3458-11e9-9b39-c2d916548a3b.png)
