### ISSUE TITLE
"Color Claim" Leading Language 

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#373]
The color(s) __________is/are claimed as a feature of the mark.

**Comment by dutchTender** [comment]
can you put a screen shot of where this should go?

**Comment by dutchTender** [comment]
??

**Comment by JackieBabos** [comment]
It needs to be displayed on the review page. 

![image](https://user-images.githubusercontent.com/44168600/53181768-37f34f80-35c6-11e9-9b1c-8c8b6d3dd06e.png)

Inbetween the Mark Literal and Mark Description fields.

**Comment by dutchTender** [comment]
ok. I will add it here under mark description

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53363310-2386be00-390a-11e9-9029-381c219f5e8a.png)

**Comment by nguyenvivi** [comment]
Please see the screenshot below.

![image](https://user-images.githubusercontent.com/46028434/53505821-a468c580-3a82-11e9-8ebf-f32dd465158a.png)

**Comment by JackieBabos** [comment]
@dutchTender see the updated text changes above in Vis comment.

**Comment by dutchTender** [comment]
i will look at this next

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53990771-05357500-40f7-11e9-9696-a7db744e32c2.png)
