### ISSUE TITLE
Reduce to Reduced Fee on Widget 

### ISSUE THREAD

**Issue by jgoldstein02** [GrantThorntonETSI/eFile_Reimagined#374]

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53114231-53e8e980-3511-11e9-8624-782aaf59bddf.png)

**Comment by nguyenvivi** [comment]
Not completed.  Please update the tag from "Reduce Fee" to "Reduced Fee".

![image](https://user-images.githubusercontent.com/46028434/53507837-9e74e380-3a86-11e9-857d-cba3881abd9b.png)

**Comment by JackieBabos** [comment]
@dutchTender need to update the blue labels throughout the application as well. See the screenshot vi placed.

**Comment by l-stanny** [comment]
@JackieBabos Updated ‘Reduce’ to ‘Reduced Fee’ in local files, will be in next GitHub push. What color are the TEAs badges supposed to be now (text and button)

**Comment by JackieBabos** [comment]
@l-stanny li made the update of the text change so you dont need to do anything on this issue.

**Comment by JackieBabos** [comment]
This has been completed.
