### ISSUE TITLE
Add s to good

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#375]
![image](https://user-images.githubusercontent.com/44168600/53106244-a077f900-3500-11e9-8406-53e3a9ded693.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53113085-b4c2f280-350e-11e9-9aee-14fefa881e69.png)

**Comment by nguyenvivi** [comment]
completed.
