### ISSUE TITLE
Attorney Bar Information Text Edit

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#377]
Replace “US” with “U.S.”

![image](https://user-images.githubusercontent.com/44168600/53182934-6ffb9200-35c8-11e9-8e2e-77f79292fb05.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53354778-84f06200-38f5-11e9-9760-6ea2844c1c21.png)
upated

**Comment by nguyenvivi** [comment]
Complete.
