### ISSUE TITLE
Owner Email Address requirement

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#378]
If the application is represented by the Attorney, then the Owner email address is **not** required.

If the application is **not** represented by the Attorney, then the Owner email address is required.

In this scenario, we have Attorney representation, therefore, the Owner email address is not required.

![image](https://user-images.githubusercontent.com/44168600/53183189-da143700-35c8-11e9-90b7-c5d372555418.png)

**Comment by dutchTender** [comment]
I  will get this next, we will need to make this update on all of the owner forms

**Comment by dutchTender** [comment]
when there is an attorney set for owner corporation. still need to apply this logic to all other owner forms.

![image](https://user-images.githubusercontent.com/7011252/53359496-11ece880-3901-11e9-9128-cf2cd52fdefc.png)

**Comment by nguyenvivi** [comment]
Complete.
