### ISSUE TITLE
Mark Literal not required for Design Only

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#380]
“Mark Literal” is not a required field for Design Only Mark.  Remove the "Reduced Fee" tag.

![image](https://user-images.githubusercontent.com/44168600/53183835-0c726400-35ca-11e9-98c1-92f6c1b94451.png)

**Comment by JackieBabos** [comment]
The mark literal is currently not a system requirement. 

Double checking if BAs meant not to have the Reduced Fee field.

**Comment by dutchTender** [comment]
removed reduce fee label for mark literal

![image](https://user-images.githubusercontent.com/7011252/53358599-c8030300-38fe-11e9-9cd7-5514d4ef6d58.png)

**Comment by nguyenvivi** [comment]
We still see the reduced fee label for mark literal.  (This testing was conducted on release version 1.0.0)

![image](https://user-images.githubusercontent.com/46028434/53506591-43da8800-3a84-11e9-93f4-915d06b358c6.png)

**Comment by JackieBabos** [comment]
Needs to be done on **Design Only**, I think you removed it from Design with Text. If so, the reduced fee label needs to be added back to Design with text.

**Comment by dutchTender** [comment]
Got it. I did remove it from both.

**Comment by JackieBabos** [comment]
Yeah thanks for adding the one back to Design with Text, but it needs to be **removed from Design ONLY**

It should not be on the mark literal for design only since this mark does not have any text.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/54560707-8f4bcc00-4988-11e9-8fe2-e1e958692bbd.png)
![image](https://user-images.githubusercontent.com/44168600/54560757-aab6d700-4988-11e9-87af-ed675cc66b4f.png)

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/54779040-996e0480-4bec-11e9-931e-078b8cff7742.png)

**Comment by l-stanny** [comment]
@dutchTender @serra-trinh @JackieBabos Current local file status of Design Only as in GitHub:
![Screen Shot 2019-03-22 at 9 31 03 PM](https://user-images.githubusercontent.com/8275852/54859975-f13e6580-4ce9-11e9-88eb-39ac60e7a323.png)

**Comment by dutchTender** [comment]
we have removed the required asteriks from mark literal field for mark type design with text.

![image](https://user-images.githubusercontent.com/7011252/55358715-0790b200-549e-11e9-8b3a-c1c022dfbf18.png)

**Comment by nguyenvivi** [comment]
This issue is closed.  Please see the newly opened issue #445 for the latest requirement.
