### ISSUE TITLE
select from contacts without entity selection

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#383]
System should not allow user to 'select from contacts' without entity type selection.

![image](https://user-images.githubusercontent.com/46028434/53503559-4a660100-3a7e-11e9-9c02-f270bd0d7c4b.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53592120-96d73c80-3b63-11e9-9e76-8409bc9a32e2.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53592144-a5255880-3b63-11e9-8bac-576c264381c8.png)
