### ISSUE TITLE
Add Additional Disclaimer

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#384]
![image](https://user-images.githubusercontent.com/46028434/53508488-da5c7880-3a87-11e9-803d-a6fafba36997.png)

**Comment by l-stanny** [comment]
@dutchTender The local implementation has been completed and pushed to GitHub

**Comment by l-stanny** [comment]
![Screen Shot 2019-04-17 at 11 07 43 AM](https://user-images.githubusercontent.com/8275852/56298968-1d8aad80-6101-11e9-98da-c202b78ba066.png)
