### ISSUE TITLE
Black and White image check box

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#388]
![image](https://user-images.githubusercontent.com/46028434/53742159-fe440380-3e65-11e9-9e7b-ffba52103cf8.png)

**Comment by dutchTender** [comment]
I will look into this as well. should be fixed in 1.0.2

**Comment by JackieBabos** [comment]
@dutchTender Is this fixed yet?

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos : @dutchTender to send @l-stanny the files to work on

**Comment by l-stanny** [comment]
![Screen Shot 2019-03-20 at 2 47 40 PM](https://user-images.githubusercontent.com/8275852/54711009-4aa66900-4b1f-11e9-9d6b-87dbc49be6c0.png)
![Screen Shot 2019-03-20 at 2 47 31 PM](https://user-images.githubusercontent.com/8275852/54711011-4b3eff80-4b1f-11e9-8536-2dda855a9908.png)
@JackieBabos @JackieBabos @serra-trinh Pushing this to Github (marks_stylized.html, marks_designonly.html, marks_design_with_text_uploaded_M5.html)

**Comment by dutchTender** [comment]
let me update this. i have not gotten to this one yet

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54953303-4cf13480-4f1e-11e9-970a-8a894a712202.png)

**Comment by dutchTender** [comment]
updated this for stylized, design only and design with text mark types
