### ISSUE TITLE
At least one good/service is in-use

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#390]
Scenario: 1(a) and 1(b) filing basis.
User selects at least one good/service is in-use.

![image](https://user-images.githubusercontent.com/46028434/53897543-5add2500-4004-11e9-9786-ce93a6d8e1b7.png)

**Comment by dutchTender** [comment]
@JackieBabos this is essentially doing the grid view here. this requires extensive development time.

**Comment by dutchTender** [comment]
will put into work que

**Comment by dutchTender** [comment]
just fyi. this is actually extremely difficult, as the number of goods and services are not set and can have variable of them. 

that means, if you select yes on questions one, and you have 5 goods and services, you have to keep track they can only select no on 4 of them. if there are 3 goods and services, you have to keep track they can only select 2 of them. and which on you select is not certain, it is any 2 of 3 of any 4 of 5 ..etc

**Comment by dutchTender** [comment]
i have no estimate on how long this would take other then it will be a very long time

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos completed locally, pushed to GitHub
