### ISSUE TITLE
Providing Specimen for 1(a) filing basis scenario.

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#391]
Scenario: 1(a) filing basis only.
User selects "Yes, the mark is in use with all of the selected goods/services."
![image](https://user-images.githubusercontent.com/46028434/53898707-9aa50c00-4006-11e9-999e-af6ae8e325dc.png)

**Comment by dutchTender** [comment]
@l-stanny  rework que

**Comment by l-stanny** [comment]
@serra-trinh This issue has been implemented locally and pushed to GitHub

**Comment by JackieBabos** [comment]
@serra-trinh and I will review.

**Comment by dutchTender** [comment]
@JackieBabos just thinking about this issue. if both in use(1a), and not in 1(b) use allow you to upload specimen at the class level and at the goods and services level ....then how are they different ???

**Comment by l-stanny** [comment]
@dutchTender @serra-trinh @JackieBabos Originally committed from local files in filename *filing_basis_abde.html* (original dev 1/19/19, additional updates to application style followed)
![Screen Shot 2019-03-22 at 9 21 33 PM](https://user-images.githubusercontent.com/8275852/54859869-acfe9580-4ce8-11e9-98f6-36b4255c5b9a.png)
Additional (current) functionality is in filename *filing_basis_ab.html* as an example of multiple classes being presented:
![Screen Shot 2019-03-22 at 9 24 20 PM](https://user-images.githubusercontent.com/8275852/54859911-19799480-4ce9-11e9-890f-90925732b227.png)
