### ISSUE TITLE
Answer changes to foreign filing questions 

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#392]
User originally selected "Yes" to the question "Do you have a registration and/or pending application in a foreign country for same goods/services?" and advanced to the next screen.  User selects both foreign registration and pending application.  Once the system displays data field for foreign registration and pending application, user selects "Previous" to return to the previous page.  User changes the selection to "No" to the question "Do you have a registration and/or pending application in a foreign country for same goods/services?" and selects "Next".  The foreign pending application and registration data fields from previous selection are still there.

**Comment by dutchTender** [comment]
I will look into this as well

**Comment by dutchTender** [comment]
setting no on the application level, should also un-set each filing basis for each class.
