### ISSUE TITLE
Change US to U.S.

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#393]
Please change "US" to "U.S."
![image](https://user-images.githubusercontent.com/46028434/53905305-3a1dcb00-4016-11e9-9b4d-fc7805883abf.png)

**Comment by dutchTender** [comment]
i should be able to get this as well

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54152297-4a1d1c80-4413-11e9-893d-12ddcb748de4.png)
