### ISSUE TITLE
Citizenship - display below Entity Type

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#396]
![image](https://user-images.githubusercontent.com/46028434/53909581-0d6eb100-4020-11e9-9402-2e04984f9576.png)

**Comment by dutchTender** [comment]
@l-stanny rework que

**Comment by dutchTender** [comment]
same as #397. this would require a complete redesign of the owner pages

**Comment by dutchTender** [comment]
@JackieBabos @nguyenvivi @serra-trinh this issue is related to #419  and is now resolved.
