### ISSUE TITLE
Display "State where legally organized" below "Entity Type"

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#397]
![image](https://user-images.githubusercontent.com/46028434/53909669-3e4ee600-4020-11e9-80ab-a1373e317828.png)

**Comment by dutchTender** [comment]
@l-stanny rework que

**Comment by dutchTender** [comment]
@JackieBabos @serra-trinh  if we were to implement this change, the owner form pages will need to be redesigned. the element that the client would like to move is part of the owner forms that is dynamic to the form that was selected.  the target location that the client wants the field to move to, its not dynamic and it is static.

**Comment by dutchTender** [comment]
@JackieBabos @nguyenvivi @serra-trinh this issue is related to #419  and is now resolved.
