### ISSUE TITLE
Edit Owner information cannot be saved

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#398]
When editing an owner and click "Done" nothing happens, and I am stuck on the Edit Owner page.

![image](https://user-images.githubusercontent.com/45850524/53966731-be795800-40c1-11e9-80bb-25fa180dcd2c.png)

**Comment by dutchTender** [comment]
@keytie can you provide which owner form was used? i could not reproduce this issue. aslo auto save occurs for each field when the user exists the input field with their mouse. hitting done always return me to the owner review screen.

**Comment by keytie** [comment]
@dutchTender It was the Sole Proprietorship.  I just tried reproducing it in the Test environment and I am no longer having the issue.  I noticed, the version is test is back to 1.0.0.  When I tested it was version 1.0.1

**Comment by dutchTender** [comment]
ok. i need to do something on the version to make it programatically. i
think the version we had was hard coded onto the page and when we did an
update, it might have been overwritten.

**Comment by keytie** [comment]
It looks like it's working in this updated release, so I'm going to close the issue.  I will reopen if I notice it again.

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/54536095-6dd9e880-4966-11e9-9be6-f9e9b0b0671e.png)
