### ISSUE TITLE
Owner name not appearing in list for Sole Proprietorship

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#399]
After adding a Sole Proprietorship owner, the individual name of the sole proprietor is listed, but this should be the Owner name (the name of the Sole Proprietorship).

![image](https://user-images.githubusercontent.com/45850524/53967194-c259aa00-40c2-11e9-9cc8-b2b1ef6d742a.png)

**Comment by dutchTender** [comment]
I will look into this next

**Comment by dutchTender** [comment]
we found that form mapping for owner sole priortorship is wrong.  we need to create special fields for owner priotorship names. this fix will be included in version 1.0.2

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/53988772-4a0add00-40f2-11e9-8ddd-01c6619bf04c.png)
this is resolved after correcting field mappings for sol p first name, last name and middle name fields. that was colliding with our display name logic.

**Comment by dutchTender** [comment]
we have addressed this issue. this will be included in 1.0.2 release.
