### ISSUE TITLE
Search does not work in Attorney Contact widget

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#400]
On the Attorney Information page, when I "Select from Contacts" and the contact widget appears, I try to search but nothing happens when I hit the magnifying glass.

![image](https://user-images.githubusercontent.com/45850524/53967936-25980c00-40c4-11e9-8fe8-6c97651471cf.png)

**Comment by dutchTender** [comment]
@l-stanny rework cue. this used to be a datatables

**Comment by dutchTender** [comment]
jackie, we need to assign this to lynn. she needs to upate this to a
datatable.

**Comment by l-stanny** [comment]
Search and Scrolling have been added to the local files for the Managed Contacts Widget and have been pushed to GitHub

**Comment by dutchTender** [comment]
i verified that @l-stanny static html working as expected. integrating this search functionality now.
