### ISSUE TITLE
Informational Message for Owner Information

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#401]
![image](https://user-images.githubusercontent.com/46028434/53969866-8bd25e00-40c7-11e9-99f1-81bf270f9226.png)

**Comment by dutchTender** [comment]
@l-stanny  rework que

**Comment by JackieBabos** [comment]
@nguyenvivi @keytie 

The URL that was commented in the screenshot above was cut off. 

Is this the correct link you would like us to use? If not, please provide the correct link.
https://www.uspto.gov/trademarks-application-process/filing-online/all-trademark-data-public

Thanks!

**Comment by nguyenvivi** [comment]
You are correct.  That is the right link.  Thank you!

**Comment by l-stanny** [comment]
@serra-trinh @dutchTender This issue has been resolved locally and pushed to GitHub 03/13/2019.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56459908-917abf00-6368-11e9-83e4-f5dd76dc7656.png)

**Comment by JackieBabos** [comment]
@nguyenvivi @keytie During the demo on 4/22 there were some discussion on this issue, please let us know how we should proceed with this issue (make the information collapsible, remove it, etc.).

**Comment by nguyenvivi** [comment]
Based on a conversation with Tina this morning, the decision was made to remove this message from the owner information module.

**Comment by JackieBabos** [comment]
@dutchTender please remove this message.

**Comment by dutchTender** [comment]
removed text form owner start page.

![image](https://user-images.githubusercontent.com/7011252/56757088-607ffd00-6761-11e9-83dd-995d3f749466.png)
