### ISSUE TITLE
use in another form is shown by default when visiting page

### ISSUE THREAD

**Issue by dutchTender** [GrantThorntonETSI/eFile_Reimagined#404]

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/54557164-e5247200-4990-11e9-9a2e-4aa57d1d43a0.png)

**Comment by l-stanny** [comment]
@dutchTender, for reference:
Local file *additional_information.html* user state 1:
![Screen Shot 2019-03-22 at 9 12 52 PM](https://user-images.githubusercontent.com/8275852/54859740-5b094000-4ce7-11e9-9059-b2d12a508288.png)
Local file *additional_information.html* user state 2:
![Screen Shot 2019-03-22 at 9 13 58 PM](https://user-images.githubusercontent.com/8275852/54859750-6fe5d380-4ce7-11e9-98f9-d8d011659ae3.png)
Local file *additional_information.html* user state 3:
![Screen Shot 2019-03-22 at 9 14 42 PM](https://user-images.githubusercontent.com/8275852/54859757-8be97500-4ce7-11e9-908a-09e95a50bbdf.png)
Local file *additional_information.html* user state 4:
![Screen Shot 2019-03-22 at 9 15 06 PM](https://user-images.githubusercontent.com/8275852/54859765-9d328180-4ce7-11e9-9a3a-7dcd22095d31.png)
Local file *additional_information.html* user state 5:
![Screen Shot 2019-03-22 at 9 15 33 PM](https://user-images.githubusercontent.com/8275852/54859769-ab809d80-4ce7-11e9-8a17-d5436347e74a.png)
Local file *additional_information.html* user state 'no', statLocal file *additional_information.html* user state 3:
![Screen Shot 2019-03-22 at 9 15 57 PM](https://user-images.githubusercontent.com/8275852/54859775-cc48f300-4ce7-11e9-9268-42bf7b06d09a.png)
