### ISSUE TITLE
Incorrect color claim statement

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#407]
![image](https://user-images.githubusercontent.com/46028434/54290828-08f74a80-4582-11e9-911b-d773bb160292.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54707037-a0c2de80-4b16-11e9-8b02-f3fe112dc183.png)
added logic to only display color claim if user selected color claim. for b&w, no color claim info is output to screen.

![image](https://user-images.githubusercontent.com/7011252/54707107-b7693580-4b16-11e9-9a4a-f35a42cc71b9.png)
