### ISSUE TITLE
Remove Email Authorization 

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#408]
![image](https://user-images.githubusercontent.com/46028434/54291326-c8e49780-4582-11e9-9df1-6a619b482443.png)

**Comment by l-stanny** [comment]
@dutchTender @JackieBabos @serra-trinh Completed locally. Will upload to GitHub next push.
![Screen Shot 2019-03-18 at 2 55 00 PM](https://user-images.githubusercontent.com/8275852/54555812-d6888b80-498d-11e9-9914-87eabaa1cdb2.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55005833-1a454b80-4fb3-11e9-895f-cd4437f84516.png)
