### ISSUE TITLE
Uploaded document thumbnail and view capability 

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#410]
This issue needs to be fixed for Scenario 2.

![image](https://user-images.githubusercontent.com/46028434/54303115-ac535a00-4598-11e9-811b-ec1e8659d067.png)

**Comment by nguyenvivi** [comment]
Thumbnail and view capability above also needs to be implemented for the Mark section/Upload Name/Portrait/Signature Consent.

![image](https://user-images.githubusercontent.com/46028434/54305531-e07d4980-459d-11e9-9a94-63cca08c623f.png)

**Comment by l-stanny** [comment]
![Screen Shot 2019-03-05 at 6 33 32 PM](https://user-images.githubusercontent.com/8275852/54859623-d4a02e80-4ce5-11e9-8ea5-0a50b9a2e0b1.png)
Local files updated 3/5/2019

**Comment by dutchTender** [comment]
@nguyenvivi a few points here.
1. this upload is for a image of the bar certificate, so it is meant for an image and not a pdf or word document.
2. because this is creating a new attorney, the upload is part of the form upload to create the new attorney, so uploaded certificate images can be seen at two places.
  I will post screen shot of the two places below

**Comment by dutchTender** [comment]
on the attorney edit page

![image](https://user-images.githubusercontent.com/7011252/55110389-4e516700-50ae-11e9-86b9-3b203ad8023e.png)

**Comment by dutchTender** [comment]
on the attorney review page, by expanding the attorney details.

![image](https://user-images.githubusercontent.com/7011252/55110420-5f01dd00-50ae-11e9-8437-1155dcf32622.png)

**Comment by nguyenvivi** [comment]
We can't test this issue.  
![image](https://user-images.githubusercontent.com/46028434/55427228-121e7a80-5576-11e9-9fc4-66c9352f28c4.png)

**Comment by JackieBabos** [comment]
Need to figure out a way to indicate to the user that the document/picture was uploaded. Or informational text indicating that the document/image is available for preview on the next page?

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55826079-2f52cc00-5ad5-11e9-8ea8-76b60d2a5983.png)
pdf support on attorney review page

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55826217-85277400-5ad5-11e9-9d23-19581ce26c5a.png)

**Comment by dutchTender** [comment]
@nguyenvivi it was agreed that the "NEXT" button is to double as submit and next. i mentioned before that this was a bad idea, but your team wanted this and we built it.

**Comment by nguyenvivi** [comment]
@dutchTender, @serra-trinh, @JackieBabos 

I thought we agreed to use PDF file for the prototype.  At least to have it ready for the customer experience.  Let's discuss this at our weekly meeting tomorrow.  

Thanks, 
V.

**Comment by dutchTender** [comment]
Vi. We have implemented support for pdf file upload and preview for
attorney bar certificate in addition to support image file types. Also
remember it was agreed that the next screen from the upload would be
attorneys edit page. To show the pdf file preview on attorney creation
success. Where as before we send the use to attorney review page after a
successful attorney creation.
But yeah. We can do a demo for you tomorrow.

Li

**Comment by JackieBabos** [comment]
@dutchTender Add the following language to the checkbox:

**I also certify that the uploaded bar credentials and certificate of good standing are accurate, and agree to upload the certificate once I click "Next."**


@nguyenvivi

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55972079-c85a2200-5c50-11e9-84d0-eb64dd282f90.png)

**Comment by keytie** [comment]
![image](https://user-images.githubusercontent.com/45850524/56365063-8e07fc00-61df-11e9-9ba7-b6a9fd8d3021.png)

**Comment by dutchTender** [comment]
@JackieBabos please open enhancement request for issue #2 here. for issue 1. please open a bug issue for it. i would like to close this ticket as it is becoming extremely difficult to track.

**Comment by dutchTender** [comment]
@JackieBabos please close this ticket when you have opened the other two tickets.

**Comment by JackieBabos** [comment]
Split this issue. 

The first comment and issue in the above picture, dealing with the certification check, is now issue #459.
The second comment and issue in the above picture, with the pdf full size, is now issue #460
