### ISSUE TITLE
Use of Previous button prevents user from going forward

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#411]
This is issue supports scenario 2.

1. User enters Attorney Information and selects "Next".
2. User then selects "Previous" to go back and adds missing required data (Bar Information)
3. System removed previously entered information.
4. User enters the information again.
3. User selects "Next" to move forward.
4.  System displays the error message as shown on the screenshot. 
![image](https://user-images.githubusercontent.com/46028434/54303639-d6594c00-4599-11e9-9837-9517b9d0fe68.png)

**Comment by dutchTender** [comment]
@nguyenvivi this functionality is implemented via the "EDIT" functionality from attorney or owner review page. hitting previous in this case is for creating an new attorney, hitting next in this case would be creating another attorney. and system in this case noted that you are trying to create an attorney with the same email.
