### ISSUE TITLE
Missing options for Name and Signature

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#412]
![image](https://user-images.githubusercontent.com/46028434/54304871-7a43f700-459c-11e9-9867-d573eee16fca.png)

**Comment by JackieBabos** [comment]
@nguyenvivi What mark type of mark is this screenshot from? Thanks!

**Comment by nguyenvivi** [comment]
This does not tie to the Mark Type.  This is the issue related to the Mark Section, Upload Consent capability.

**Comment by JackieBabos** [comment]
@nguyenvivi Is this for scenario 2? Which is a design only mark, only portrait would appear according to the TMRD.

![image](https://user-images.githubusercontent.com/44168600/54564200-c920d080-4990-11e9-8bf6-11e104f5da07.png)

**Comment by JackieBabos** [comment]
Holding off for now.

**Comment by l-stanny** [comment]
The local file has this in Design Only (file *marks_designonly.html*): 
![Screen Shot 2019-03-22 at 8 58 07 PM](https://user-images.githubusercontent.com/8275852/54859585-4a57ca80-4ce5-11e9-9ca6-cf91dc5c9eb7.png)

**Comment by JackieBabos** [comment]
"For purposes of the prototype, I think we can keep it restricted by Mark type according to the TM-RD.  My thought is, if it isn’t applicable to the selected mark type, why give the user the option, and potentially get unwanted information. " 

Closing this issue due to no longer being relevant.
