### ISSUE TITLE
1(b) filing basis only with multiple goods/services

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#413]
This is a high priority issue.  We need this functionality for Scenario 2.

Select 1(a) and 1(b) filing basis:
![image](https://user-images.githubusercontent.com/46028434/54306215-43231500-459f-11e9-8a1a-f17dcc6ee323.png)

User should be able to select 1(b) filing only by answering "No" as shown below.  Currently the system prevents the user from selecting "No" all the way through.

![image](https://user-images.githubusercontent.com/46028434/54306640-33580080-45a0-11e9-8459-71433a3900fc.png)

**Comment by l-stanny** [comment]
@dutchTender @JackieBabos @serra-trinh This functionality was built into *filing_basis_ab.html*. GitHub push "#389 + #390" (both) 3/20/2019.
![Screen Shot 2019-03-22 at 7 13 59 PM](https://user-images.githubusercontent.com/8275852/54857700-1c6b8980-4cd7-11e9-9f45-b0791e4b81f7.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55257752-3c4f0000-5237-11e9-84d4-b50f56d9a6c7.png)
