### ISSUE TITLE
Select from Contacts does not work for Foreign Entity

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#420]
![image](https://user-images.githubusercontent.com/46028434/54535889-e7bda200-4965-11e9-9aed-499fe3b3c6a0.png)

**Comment by dutchTender** [comment]
I will look into this.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55111708-64acf200-50b1-11e9-8c8a-40b67c1c2bb8.png)


still need to add auto fill functionality

**Comment by JackieBabos** [comment]
Discussed during the demo we can look into issue #258 to have the owner name populate for partnership and corporation from contact widget.
