### ISSUE TITLE
Owner Edit Page does not capture previously entered information

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#421]
![image](https://user-images.githubusercontent.com/46028434/54536146-82b67c00-4966-11e9-89c9-e177871ebd9a.png)

**Comment by dutchTender** [comment]
@JackieBabos i was not able to reproduce this in the BA servers and our internal stage servers.

**Comment by dutchTender** [comment]
@JackieBabos let me try foreign entity, this might be foreign

**Comment by JackieBabos** [comment]
@dutchTender I was able to recreate it. Let me know if we need to talk about this one. 

From the creation page:
![image](https://user-images.githubusercontent.com/44168600/54564788-48fb6a80-4992-11e9-98d7-740b0f2336a6.png)

From the edit page:
![image](https://user-images.githubusercontent.com/44168600/54564802-557fc300-4992-11e9-95fe-7ae9b486b190.png)

**Comment by dutchTender** [comment]
oh, i see, foreign info edit. let me look into this

**Comment by dutchTender** [comment]
@nguyenvivi one of the problems here is that we were asked to make the entity type name for foreign corporation to 'corporation' just like domestic corporation. we load the edit forms based on types. 
for this to work, we would need to design a new scheme to differentiate between entity types.

**Comment by dutchTender** [comment]
@nguyenvivi we were able to design a work around for this issue. we are using a special variable to track this field, and will dispaly country or state based on foreign or u.s for corporation owner types.

![image](https://user-images.githubusercontent.com/7011252/54690699-56cb0000-4af8-11e9-99e8-7fbfed712bac.png)
