### ISSUE TITLE
Owner Edit Page - State should be a text box

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#422]
![image](https://user-images.githubusercontent.com/46028434/54536512-3b7cbb00-4967-11e9-9d5e-c8b664a85126.png)

**Comment by dutchTender** [comment]
@nguyenvivi @JackieBabos i am guessing this is for foreign entities only?

**Comment by nguyenvivi** [comment]
@dutchTender - This is for everything, including foreign entities.

**Comment by dutchTender** [comment]
making this update now. will need to update this for owner edit as well. a slight more complex here cause its foreign corporation

**Comment by dutchTender** [comment]
@nguyenvivi never mind. this is for every thing. less complex, but a good amount of upates as we have a few of these owner edit forms and import forms.

**Comment by nguyenvivi** [comment]
Based on SME comments, we need to update the prototype as follows:
1.  If it's U.S. entity, the State data field should be displayed as a drop down list and it should be populated with U.S. States.
2.  If it's a Foreign entity, the State data field should be displayed as a text field.
3. The behaviors should be the same for the Owner Page and Owner Edit Page.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55562375-cb3d9b80-56c1-11e9-90a4-c56916d9d22f.png)
