### ISSUE TITLE
Default selection for Trademark/Servicemark

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#425]
![image](https://user-images.githubusercontent.com/46028434/54538408-9368f100-496a-11e9-9d51-1e5ce1f65af7.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54624206-4efd5400-4a43-11e9-997d-9d41ba50de6e.png)
check mark is set by default.    will update required fields.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54624912-ad770200-4a44-11e9-93b8-98c964072791.png)
added requested info test

**Comment by JackieBabos** [comment]
Move text above the tile.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54768590-dc70ad80-4bd5-11e9-8ecc-6a6fee1a1a11.png)

**Comment by l-stanny** [comment]
![Screen Shot 2019-03-22 at 7 27 59 PM](https://user-images.githubusercontent.com/8275852/54857992-b54ed480-4cd8-11e9-8e00-bdafbd2f81b8.png)
@JackieBabos @serra-trinh Updated and pushed to GitHub.

**Comment by JackieBabos** [comment]
Related to issue #282
