### ISSUE TITLE
Mark image not being displayed

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#426]
![image](https://user-images.githubusercontent.com/46028434/54538574-de830400-496a-11e9-98e5-8300e27a03e4.png)

**Comment by dutchTender** [comment]
I will address this issue next

**Comment by JackieBabos** [comment]
@dutchTender  Not sure if it matters but the mark image is shown on the attorney page 

![image](https://user-images.githubusercontent.com/44168600/54563601-3a5f8400-498f-11e9-9942-48368126e440.png)

**Comment by dutchTender** [comment]
my idea was to have that there to be consistent with the ui layout, but will have it to shown blank or deactivated or something.

**Comment by dutchTender** [comment]
like what happens when you revisit via bread crumbs ...so instead of having it show up later when you revisit, it is a bit easier to always have  it there, but only show the image when there is one, show a default image when mark isn't uploaded yet

**Comment by dutchTender** [comment]
still need to update other pages that has this defect.

goods and services, filing basis
