### ISSUE TITLE
Mark Literal is TEAS Plus required for all marks with text

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#427]
![image](https://user-images.githubusercontent.com/46028434/54539487-9bc22b80-496c-11e9-87f0-590e59544828.png)

**Comment by dutchTender** [comment]
i could swear this was required and i was asked to make this not required for stylized. I would need to go through the old issues

**Comment by JackieBabos** [comment]
@dutchTender i think you were thinking of Design Only which doesn't need the flag, which was issue #380. So stylized and design with text need the reduced flags next to them.

**Comment by nguyenvivi** [comment]
@dutchTender and @JackieBabos 

Jackie, you are correct, for any design with text, the mark literal is required for TEAS Plus status.  "Stylize" has text, that's why we are asking for making this field as required data for TEAS Plus.  I know it's confusing.  Hope it makes sense now.

**Comment by dutchTender** [comment]
I have added the reduced fee label back just for mark type stylized.
![image](https://user-images.githubusercontent.com/7011252/54559799-40596300-4997-11e9-9c08-50e4f96deb70.png)

**Comment by JackieBabos** [comment]
Remove the red asterisk for mark literal, relocate the "i" on the last text of mark literal.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54767754-3d978180-4bd4-11e9-964e-97b37deb41a0.png)

**Comment by l-stanny** [comment]
@JackieBabos @serra-trinh Local files uploaded and pushing to GitHub
![Screen Shot 2019-03-22 at 6 50 47 PM](https://user-images.githubusercontent.com/8275852/54857012-88e48980-4cd3-11e9-84d8-73dacb1a0e1d.png)
![Screen Shot 2019-03-22 at 6 50 15 PM](https://user-images.githubusercontent.com/8275852/54857013-897d2000-4cd3-11e9-93ec-4c285c910311.png)
![Screen Shot 2019-03-22 at 6 49 45 PM](https://user-images.githubusercontent.com/8275852/54857014-8a15b680-4cd3-11e9-9970-fd285a208e53.png)

**Comment by nguyenvivi** [comment]
We will close this issue as this will be addressed by an issue (number???) that GT will open.  

From Albert Young:

I just spoke with Tanya and Matt Schwab.  The Mark literal field is NOT required at the time of filing, NOR is it required for TEAS Plus status, with the exception of a standard character marks.

The legal requirement for the mark (drawing) is for the image, not the literal element.  Please remove the “*” from the mark literal field for all marks types except standard character mark.  Also, please remove the “Reduced fee” tag from the literal element field for all mark types.  

Please let us know if you have any questions or concerns.  Thanks!

**Comment by JackieBabos** [comment]
Will be addressed in Issue #455

**Comment by nguyenvivi** [comment]
Sorry Jackie and Li, what I meant to close is issue #380.

**Comment by nguyenvivi** [comment]
We tested this issue for TEAS Plus status and it works for Standard Character, Stylized, and Design with Text.
