### ISSUE TITLE
"Return to application" does not work for Foreign Application.

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#428]
![image](https://user-images.githubusercontent.com/46028434/54540147-d4aed000-496d-11e9-8079-816bdaf029dc.png)

**Comment by dutchTender** [comment]
selected owner type foreign corporation.

and selected foreign registration but did not provide dates and and upload a certificate

![image](https://user-images.githubusercontent.com/7011252/54558618-92e55000-4994-11e9-94dd-7ffc5e58f868.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54558918-3df60980-4995-11e9-95fd-f4d22344ee4d.png)

**Comment by dutchTender** [comment]
hitting the return to application button takes me to the filing basis page, which is what is expected in this case as the missing TEAS files is filing basis registration info

![image](https://user-images.githubusercontent.com/7011252/54558982-5ebe5f00-4995-11e9-93ef-be630ce6b8c7.png)

**Comment by dutchTender** [comment]
@nguyenvivi we may need steps from you to recreate the issue. I talked to Jackie and she is testing this too and get back to me.

**Comment by nguyenvivi** [comment]
@dutchTender - we can walk you through the scenario tomorrow if you have time.

**Comment by nguyenvivi** [comment]
@dutchTender - hitting the return to application button should take me back to the missing data fields, in this case is the foreign registration date, not the filing basis selection screen.  

from Li's previous message:
> hitting the return to application button takes me to the filing basis page, which is what is expected in this case as the missing TEAS files is filing basis registration info
> ![image](https://user-images.githubusercontent.com/7011252/54558982-5ebe5f00-4995-11e9-93ef-be630ce6b8c7.png)

**Comment by dutchTender** [comment]
@nguyenvivi understood, i thought you were getting an error. i am looking into updating this now.
