### ISSUE TITLE
Foreign Registration renewal date is not required for TEAS Plus status

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#430]
![image](https://user-images.githubusercontent.com/46028434/54540391-50108180-496e-11e9-989c-13a83ba621be.png)

**Comment by dutchTender** [comment]
removed reduced fee lablel for renewal date

![image](https://user-images.githubusercontent.com/7011252/54551344-4db92200-4984-11e9-8524-de76ab69b55a.png)
