### ISSUE TITLE
Update Mark Literal text

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#432]
![image](https://user-images.githubusercontent.com/46028434/54556250-d937b080-498e-11e9-8aa6-ee9e5c37c16b.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54644258-576b8400-4a6f-11e9-89df-0f5c09423242.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos This edit has been completed in local file *marks_design_with_text_uploaded_M5.html* and will be in the next GitHub push.
