### ISSUE TITLE
Remove leading language for mark literal/standard character

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#433]
![image](https://user-images.githubusercontent.com/46028434/54556719-dc7f6c00-498f-11e9-8f0d-3061d49b36d2.png)

**Comment by l-stanny** [comment]
@JackieBabos @serra-trinh This page has been updated locally and will be in the next GitHub push.
![Screen Shot 2019-03-22 at 6 25 28 PM](https://user-images.githubusercontent.com/8275852/54856273-00181e80-4cd0-11e9-95f0-a1c201d77441.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54948879-19111180-4f14-11e9-977f-259319c6e5e4.png)
application updated.
