### ISSUE TITLE
Citizenship should not be displayed in the Review page for LLC entity type

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#439]
![image](https://user-images.githubusercontent.com/46028434/54633863-66463c80-4a57-11e9-8186-66c6c6cce3de.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54948407-f2061000-4f12-11e9-8bd9-2610dc7bc09f.png)
we updated this for all owner types that are not humans.
