### ISSUE TITLE
Update label to General Partner Name

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#441]
![image](https://user-images.githubusercontent.com/46028434/54774650-9b32ca80-4be2-11e9-8f10-ae13bb43370a.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54935064-f07a1f00-4ef5-11e9-84b4-439bf92ac606.png)

**Comment by dutchTender** [comment]
@nguyenvivi what should the label name for "owner name" changed for trust, llp and estate. i am guessing it should not say "General partners"
