### ISSUE TITLE
TEAS Plus status for Attorney Affiliation Information

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#442]
![image](https://user-images.githubusercontent.com/46028434/54925073-f6670480-4ee3-11e9-9df8-5e7c9ec2e999.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/54930230-4bf3df00-4eed-11e9-9b31-8490feb7a196.png)

added labels ...still need to add validation back end logic for application review module

**Comment by dutchTender** [comment]
@nguyenvivi a few things there. are these information TEAS plus required for the primary attorney or all attorneys added to the application.

**Comment by nguyenvivi** [comment]
@dutchTender these are for TEAS Plus status and for primary attorney.

**Comment by dutchTender** [comment]
@nguyenvivi got it

**Comment by JackieBabos** [comment]
@dutchTender need to remove the asterisk next to "Attorney Bar Info"
