### ISSUE TITLE
Provide informational text for Owner of mark

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#443]
![image](https://user-images.githubusercontent.com/46028434/55007473-dacc2e80-4fb5-11e9-8bfb-af28b65944de.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos this has been completed locally and the files pushed to GitHub.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55509297-b7def180-5629-11e9-91ce-521f184075ff.png)
