### ISSUE TITLE
Add informational text for Alternate Name

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#444]
![image](https://user-images.githubusercontent.com/46028434/55008857-07814580-4fb8-11e9-88e2-9c732482908a.png)

**Comment by JackieBabos** [comment]
Need to take off the colon. 
![image](https://user-images.githubusercontent.com/44168600/55338215-6da91500-545d-11e9-816b-1e2f6efff70b.png)

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/55424244-52c6c580-556f-11e9-9ae7-7e72131df74c.png)
