### ISSUE TITLE
Update text for Translation and Transliteration

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#445]
![image](https://user-images.githubusercontent.com/46028434/55018802-f6413480-4fc9-11e9-95eb-63e567c1c961.png)
![image](https://user-images.githubusercontent.com/46028434/55019045-841d1f80-4fca-11e9-90a9-9c44f73b7233.png)

**Comment by nguyenvivi** [comment]
![image](https://user-images.githubusercontent.com/46028434/55019606-9e0b3200-4fcb-11e9-9b38-9b0d40b2e3a0.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos this has been completed locally and the files pushed to GitHub.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55256959-df524a80-5234-11e9-9aff-7c8fb9857e47.png)

**Comment by nguyenvivi** [comment]
Transliteration issue: This is not correct.  For legal purposes, the statement MUST appear as follows:

and this means [xxxxx] in English.
[xxxx] represents a text box in this scenario.

![image](https://user-images.githubusercontent.com/46028434/55424012-ccaa7f00-556e-11e9-92d1-44d1caafd8f3.png)

**Comment by JackieBabos** [comment]
Need to move the text box in between "and this means" and "in English".
