### ISSUE TITLE
Update informational text to Name/Portrait/Signature

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#446]
![image](https://user-images.githubusercontent.com/46028434/55021518-41117b00-4fcf-11e9-811e-87cc4eecd86b.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos completed locally

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55256149-c052b900-5232-11e9-94c5-2e9458c5d238.png)
