### ISSUE TITLE
Dynamic Consent Template

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#447]
"If the system could be dynamic enough to where the template would be populated with the right language based on how the user answers the name/portrait/consent section of the application. That way, only one template would be needed as opposed to three." - Al

**Comment by JackieBabos** [comment]
[Consent_template_Name_Signature.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081146/Consent_template_Name_Signature.docx)
[Consent_template_Name_Portrait_Signature.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081147/Consent_template_Name_Portrait_Signature.docx)
[Consent_template_Portrait_Signature.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081148/Consent_template_Portrait_Signature.docx)
[Consent_template_Name_Portrait.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081149/Consent_template_Name_Portrait.docx)
[Consent_template_Signature.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081150/Consent_template_Signature.docx)
[Consent_template_Name.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081151/Consent_template_Name.docx)
[Consent_template_Portrait.docx](https://github.com/GrantThorntonETSI/eFile_Reimagined/files/3081152/Consent_template_Portrait.docx)

**Comment by dutchTender** [comment]
adding these now

**Comment by dutchTender** [comment]
design only -  can be  "name", "portrait" or "name and portrait".
