### ISSUE TITLE
Name/Portrait/Signature TEAS Plus validation

### ISSUE THREAD

**Issue by nguyenvivi** [GrantThorntonETSI/eFile_Reimagined#449]
![image](https://user-images.githubusercontent.com/46028434/55423311-2dd15300-556d-11e9-9b5b-4b911937a32a.png)

**Comment by keytie** [comment]
![image](https://user-images.githubusercontent.com/45850524/56379163-97ed2780-61fe-11e9-9699-33e52bcfc84a.png)

![image](https://user-images.githubusercontent.com/45850524/56379178-a0456280-61fe-11e9-8dca-e4142c28f6e9.png)

**Comment by JackieBabos** [comment]
The comment above that reopened this issue is now issue #458
