### ISSUE TITLE
Specimen Checkboxes

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#452]
When the User selects "One specimen for all goods/services within this class", then within each individual good or service, the checkbox "Check here to provide a specimen for this individual good/service" should be removed. Since the user uploaded the specimen at the class level.
![image](https://user-images.githubusercontent.com/44168600/55633991-be30b300-577a-11e9-9102-4e791d36c047.png)
![image](https://user-images.githubusercontent.com/44168600/55633997-c0930d00-577a-11e9-8cf1-8ed8ed170e0b.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55657049-02e23b80-57c7-11e9-8d21-851744304cb3.png)
