### ISSUE TITLE
Mark Literal - Remove Asterisk

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#455]
I just spoke with Tanya and Matt Schwab.  The Mark literal field is NOT required at the time of filing, NOR is it required for TEAS Plus status, with the exception of a standard character marks.

The legal requirement for the mark (drawing) is for the image, not the literal element.  Please remove the “*” from the mark literal field for all marks types except standard character mark.  Also, please remove the “Reduced fee” tag from the literal element field for all mark types.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/55746854-d9b0ed80-5a08-11e9-9205-a04356414405.png)
removed asteriks and reduced fee label. still need to remove logic for flagging this field.
