### ISSUE TITLE
Color/Translation/Transliteration Reduced Fee Flagging

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#458]
Splitting issue #449, with the information that @keytie posted that needs to be updated in order to close the issue. 

![image](https://user-images.githubusercontent.com/44168600/56504013-7200a500-64d4-11e9-894c-8c65d075d432.png)
 
![image](https://user-images.githubusercontent.com/44168600/56504035-817fee00-64d4-11e9-8b14-702f5ba19c8b.png)

**Comment by dutchTender** [comment]
the foreign wording is flagged only when you select yes for transliteration, it does not flag it if you do not set that value or answered no. that appears to be the correct logic. the change for issue #458 would be to flag foreign wording even if the user does not answer yes or no for transliteration. which would not even show the foreign wording input

**Comment by dutchTender** [comment]
after speaking with jackie. logic for this have been updated to so that if transliteration or translation is not set, then no fields from this module is flagged. only if they are set to yes, then the filer must provide foreign wording text.

**Comment by JackieBabos** [comment]
Need further discussion with the BAs. Mark description is always TEAs Plus required. However, color claim is optional, and in the prototype we have mark description in color claim. So if the user omits answer yes/no to color claim they don't fill in the mark description and will get flagged on the TEAs plus review page. 

![image](https://user-images.githubusercontent.com/44168600/56508656-189f7280-64e2-11e9-9ba5-d2915d86e9a6.png)

**Comment by JackieBabos** [comment]
Move "Mark Description" out of the color claim box, and place above color claim and below mark literal. 

Then make color claim like translation and transliteration, when the user doesn't select either yes/no on color claim the reduced fee flag will not appear on the TEAs plus review page.

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56666363-c002dd80-6679-11e9-832c-f0ff531a70d7.png)
moved mark description out of color claim

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56669732-9cdb2c80-667f-11e9-8646-8c101240c4a7.png)

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56679019-0f550800-6692-11e9-92e6-3fa46f3e5b11.png)
mark type stylized

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56742468-cc9f3880-6742-11e9-8d46-5e123c62c375.png)

**Comment by dutchTender** [comment]
fix this

**Comment by dutchTender** [comment]
fixed double teas plus labels for mark description.

![image](https://user-images.githubusercontent.com/7011252/56755070-a5edfb80-675c-11e9-92f1-81c7e4eca51d.png)
