### ISSUE TITLE
Attorney Edit Page - Certification Check 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#459]
![image](https://user-images.githubusercontent.com/44168600/56512539-e8a99c80-64ec-11e9-8c2c-8863014726f7.png)

**Comment by dutchTender** [comment]
add persistence behavior for check box

**Comment by dutchTender** [comment]
![image](https://user-images.githubusercontent.com/7011252/56687508-711e6d80-66a4-11e9-8263-fa9b2c8b3993.png)
