### ISSUE TITLE
petitions rework based on BA's feed back

### ISSUE THREAD

**Issue by dutchTender** [GrantThorntonETSI/eFile_Reimagined#468]

**Comment by dutchTender** [comment]
1. need feed back from the BA's on if the required actions should also be paged ...just like the options actions.

2. need feed back on the statuses of the revivied filings

3. if the bread crumb idea is a go.


4. add accoridan for all application pages.

5. get some clearification on documents. ....we can start this part

**Comment by JackieBabos** [comment]
Completed.
