### ISSUE TITLE
Add more data to the users contact lists/No data in manage contacts

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#469]
The contacts in the manged contacts were not being saved, so the users had no contacts in their list. 

"When entering owner info, selecting from contacts doesn't enter any information. Even with the green check mark no data is available."

**Comment by JackieBabos** [comment]
This has been resolved.

**Comment by dutchTender** [comment]
oh ok. this is probably issues that vi found.
