### ISSUE TITLE
Return to Application - Error

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#470]
Saw the ‘puppies’ image again when I tried to go back to update the required TEAS Plus data fields.

![image](https://user-images.githubusercontent.com/44168600/58185165-bc11ad80-7c6f-11e9-9fe0-eaaedc862bef.png)

**Comment by dutchTender** [comment]
is this the same issue that Vi had??

**Comment by JackieBabos** [comment]
No longer an issue.
