### ISSUE TITLE
Better alert to the customers that this is a Chrome application 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#471]

**Comment by JackieBabos** [comment]
File dashboard.html in Internet Explorer

**Comment by l-stanny** [comment]
Added alert for IE, suggesting Chrome. Now adding alert for anything other than Chrome, suggesting Chrome.

**Comment by JackieBabos** [comment]
Place the warning on the main landing page as well.
