### ISSUE TITLE
Show selected file, then have the upload button enabled (Upload process more intuitive)

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#472]
Suggest   adding "File selected" with the file name extension, and then   upload button becomes enabled (Mark image (ST))

**Comment by l-stanny** [comment]
![Screen Shot 2019-05-30 at 12 30 48 PM](https://user-images.githubusercontent.com/8275852/58648163-172e4a80-82d7-11e9-9f96-62e3735601ea.png)
![Screen Shot 2019-05-30 at 12 30 37 PM](https://user-images.githubusercontent.com/8275852/58648166-17c6e100-82d7-11e9-9834-99f18379efd7.png)
![Screen Shot 2019-05-30 at 12 34 16 PM](https://user-images.githubusercontent.com/8275852/58648241-4b097000-82d7-11e9-840b-e36b8e0cf031.png)
![Screen Shot 2019-05-30 at 12 34 06 PM](https://user-images.githubusercontent.com/8275852/58648248-4ba20680-82d7-11e9-90fd-f2cba3a08482.png)
![Screen Shot 2019-05-30 at 12 33 55 PM](https://user-images.githubusercontent.com/8275852/58648251-4c3a9d00-82d7-11e9-8219-797ce81ee1e2.png)
@JackieBabos with larger 'thumbnail' images also as requested.
