### ISSUE TITLE
Add guidance for password creation

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#473]
Add   standard password creation language used by MyUSPTO - add applicable language   based on the design
--

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/58569970-5c2d8080-81f4-11e9-8a1b-793572070afc.png)
 This is MyUSPTO guidance.

**Comment by JackieBabos** [comment]
File create_account.html

**Comment by keytie** [comment]
![2019-06-18_11-11-25](https://user-images.githubusercontent.com/45850524/59696412-eea0be80-91b9-11e9-8187-76614addc20e.png)
 This message should also be on the password reset page.

**Comment by dutchTender** [comment]
got it. i will make that update.
