### ISSUE TITLE
Split Screen Hides Scroll Bar Content

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#494]
If the screen is collapsed, you cannot see everything even with the scroll bar.

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos @dutchTender Fixed in application and merged in GitHub 7/24/2019.
![Screen Shot 2019-07-24 at 1 15 05 PM](https://user-images.githubusercontent.com/8275852/61814828-ee2dc000-ae16-11e9-868d-0807c49485cb.png)
