### ISSUE TITLE
Add document upload instructions text

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#497]
Add document upload "instructions" to be consistent with previous document up loaders that list the types of documents you can upload there.  

![image](https://user-images.githubusercontent.com/44168600/61225942-d0f24680-a6de-11e9-849b-02f05d7a5c5b.png)

**Comment by JackieBabos** [comment]
-Trademark Details: Design
-Trademark Details: Design with text
-Trademark Details: Stylized
-Trademark Details: Stylized -> name, portrait, signature -> upload consent
-Filing Basis (when mark is currently in use is selected)
-Filing Basis -> Foreign Registration Certificate
-Additional Information: Optional Upload
-Claim of Acquired Distinctiveness (when yes/whole/distinctive are all selected)
-Concurrent Use (when court decree is selected)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos This was completed and local files and committed to GitHub on 7/19/2019.
