### ISSUE TITLE
Text Box Can be Reshaped by User

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#500]
On the bottom right hand corner of the text field after 'Provide the additional information,' you can drag and reshape the text box.

**Comment by nicksummersadta** [comment]
Expanding text boxes

**Comment by nicksummersadta** [comment]
Lynn will disable adjustment functionality, only use scroll bar

**Comment by l-stanny** [comment]
This has been updated locally. Updating in application. 
![Screen Shot 2019-07-24 at 7 03 41 PM](https://user-images.githubusercontent.com/8275852/61834407-d6216500-ae45-11e9-9c65-9c7567cd5ba7.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos @dutchTender This has been completed using Maven for merging into the application.
![Screen Shot 2019-07-24 at 8 10 30 PM](https://user-images.githubusercontent.com/8275852/61836677-45e81d80-ae4f-11e9-872c-9f9933b4d951.png)

**Comment by keytie** [comment]
example - Mark Description Box
