### ISSUE TITLE
Improve 'new application' button

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#501]
Make the New Application button bigger/more visible and potentially change it to 'Create New Application' to make it easier for the user to know where to start.

**Comment by l-stanny** [comment]
Implemented in local files 7/30/2019. 
![Screen Shot 2019-07-30 at 3 47 44 PM](https://user-images.githubusercontent.com/8275852/62561189-9b0f3080-b84c-11e9-9d8d-0efd0d900eb8.png)
![Screen Shot 2019-07-30 at 3 45 40 PM](https://user-images.githubusercontent.com/8275852/62561193-9ba7c700-b84c-11e9-81cd-6ac9fc3d22ed.png)

**Comment by JackieBabos** [comment]
Move back to the upper right hand side of the "Filing Table". @l-stanny

**Comment by JackieBabos** [comment]
Completed.
