### ISSUE TITLE
Stack boxes on dashboard vertically

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#502]
Break the page up into Filings and Upcoming Actions stacked   horizontally on top of the other.  Announcements is fine on the right side.  If you're logging in for the first time, it can be confusing and distract from what you came here to do (create a new application)

**Comment by l-stanny** [comment]
Mocking up.

**Comment by l-stanny** [comment]
Implemented in local files 7/30/2019 
![Screen Shot 2019-07-30 at 3 47 44 PM](https://user-images.githubusercontent.com/8275852/62561112-7dda6200-b84c-11e9-91b6-73e67fc680d0.png)
![Screen Shot 2019-07-30 at 3 45 40 PM](https://user-images.githubusercontent.com/8275852/62561113-7e72f880-b84c-11e9-958d-9ce69e8658dd.png)

**Comment by keytie** [comment]
This is not in the test environment, so cannot test or close.

**Comment by JackieBabos** [comment]
@keytie I messaged Li, your stage server is now up to date.
