### ISSUE TITLE
Date Picker Move Forward Years

### ISSUE THREAD

**Issue by nicksummersadta** [GrantThorntonETSI/eFile_Reimagined#506]
Add the option to go back or forward by year as well as month in the date field

**Comment by nicksummersadta** [comment]
Lynn to create 2-3 options for team to choose

**Comment by JackieBabos** [comment]
Showed option to BAs.

**Comment by l-stanny** [comment]
@serra-trinh @dutchTender @JackieBabos Implemented across local files and committed 7/31/2019.
