### ISSUE TITLE
Contacts Widget - 'Add' button is cut off

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#513]
Fix the contacts widget to not have the add button be cut off. 

![image](https://user-images.githubusercontent.com/44168600/61395364-84477080-a882-11e9-8701-1d522aaec4e5.png)

**Comment by l-stanny** [comment]
@serra-trinh @JackieBabos @dutchTender This was completed and merged into the application files on 7/23/2019.
