### ISSUE TITLE
Add Informational Text for the Reduced Fee Mode 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#521]
Need to add informational text for what the reduced fee mode is.

**Comment by keytie** [comment]
Receive a lower application fee when all fields marked with the reduced fee indicator are completed.

**Comment by JackieBabos** [comment]
@l-stanny Please use the message that keyte posted above as the informational message.

**Comment by l-stanny** [comment]
Implemented in local files 8/6/2019.
<img width="504" alt="Screen Shot 2019-08-05 at 2 22 07 PM" src="https://user-images.githubusercontent.com/8275852/62560984-2fc55e80-b84c-11e9-9ef2-4976e1150a71.png">
<img width="472" alt="Screen Shot 2019-08-05 at 2 22 03 PM" src="https://user-images.githubusercontent.com/8275852/62560986-305df500-b84c-11e9-9674-a32a09356758.png">
