### ISSUE TITLE
Application Data Drop down on SOU and Post Reg

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#539]
On the SOU Petition and Post Registration Page the "Application Data" dropdown at the top of the page should display the application data.

![image](https://user-images.githubusercontent.com/44168600/63400714-07804880-c392-11e9-9e5b-67accde0279d.png)

![image](https://user-images.githubusercontent.com/44168600/63400743-24b51700-c392-11e9-9fc1-fc8c5d121702.png)

**Comment by dutchTender** [comment]
this is done. will update stage server soon.
