### ISSUE TITLE
SOU Upload 

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#541]
The upload in the Statement of Use is not working. 

![image](https://user-images.githubusercontent.com/44168600/63436375-cf0a5a00-c3e5-11e9-8782-7981ac31be0b.png)

**Comment by dutchTender** [comment]
i believe this is done as well.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/65104529-ee69b800-d98e-11e9-9747-c377ee0d2d0a.png)
