### ISSUE TITLE
Update Post Reg Optional Actions Page

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#546]
Have the actions for the Post Reg Optional Actions to match the file *Post_Reg_Optional*

![image](https://user-images.githubusercontent.com/44168600/63598556-0c552000-c57d-11e9-9719-a3e96e40d5cd.png)

**Comment by dutchTender** [comment]
jackie. this have been updated and is now on the stage server
