### ISSUE TITLE
Registration Number on Upcoming Actions Due table

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#549]
The registration number that appears on the 'Filing' table should also appear on the "Upcoming Action Due" table. (Yellow Highlight)

![image](https://user-images.githubusercontent.com/44168600/63699637-77e9f800-c7de-11e9-92e6-4099e41eeae2.png)

**Comment by dutchTender** [comment]
i believe this is done
