### ISSUE TITLE
Incorrect Status for SOU - Abandoned - Failure to File Timely SOU or Extension Request

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#563]
The status description should be updated as follows (This is for scenario 1):

![image](https://user-images.githubusercontent.com/45850524/64721502-9f0d1e80-d49a-11e9-85dc-562502e36c4d.png)

**Comment by dutchTender** [comment]
let me check it out. i thought we fixed this.

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/64930803-3a7ef600-d7f1-11e9-9d63-36a8af28f960.png)
