### ISSUE TITLE
Post Registration Action is incorrect

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#566]
![image](https://user-images.githubusercontent.com/45850524/64807965-4c983480-d564-11e9-8a4e-6f97d710f84b.png)

**Comment by JackieBabos** [comment]
@dutchTender  the status and action title for post reg (screenshot below) is still incorrect.  The *status* needs to be "Registered" and the *action* needs to be "File Section 8 Declaration" 

![image](https://user-images.githubusercontent.com/44168600/64930972-5931bc80-d7f2-11e9-8b2f-2e24e9541bd7.png)

**Comment by dutchTender** [comment]
ok. working on it,

**Comment by JackieBabos** [comment]
![image](https://user-images.githubusercontent.com/44168600/65104391-85824000-d98e-11e9-9507-639302164c15.png)
