### ISSUE TITLE
Post Registration - Section 8 - Shows Office Action instead of Section 8 - can't proceed

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#567]
Testing Scenario 2 - Post Registration:
I get this Action (should be File Section 8 Declaration) 
![image](https://user-images.githubusercontent.com/45850524/64809902-3be9bd80-d568-11e9-9d32-7de732b8b5a8.png)

I click the Action and I get this page, where there is nothing to do (I can't proceed) - and I can't file the Section 8.
![image](https://user-images.githubusercontent.com/45850524/64810028-8f5c0b80-d568-11e9-9aa5-0b2befdc00ce.png)
![image](https://user-images.githubusercontent.com/45850524/64810066-a7338f80-d568-11e9-8c6f-d8bf6bd03e20.png)

**Comment by dutchTender** [comment]
issue fixed. updating servers very soon.

**Comment by dutchTender** [comment]
seeing the same behavior in some cases for SOU petition
