### ISSUE TITLE
Petition Signature - Required fields are not indicated with an asterisk

### ISSUE THREAD

**Issue by keytie** [GrantThorntonETSI/eFile_Reimagined#572]
Required signature fields are not marked as required on the petition signature, as it is for other signature fields.  

![image](https://user-images.githubusercontent.com/45850524/64813835-46a85080-d570-11e9-8fc8-984b52e8f4be.png)

**Comment by JackieBabos** [comment]
Need to add the asterisks to the following fields.
![image](https://user-images.githubusercontent.com/44168600/64931057-32c05100-d7f3-11e9-9b6b-9cd2cc43f37e.png)

**Comment by dutchTender** [comment]
I will get this today.

**Comment by JackieBabos** [comment]
Looks good on SOU Petition,  Post Reg, and Office action petition.
