### ISSUE TITLE
Auto save notification

### ISSUE THREAD

**Issue by JackieBabos** [GrantThorntonETSI/eFile_Reimagined#80]
Remove the green text that pops up that shows that the information is saved, and add a "Last Saved" time or something in one of the corners of the page.

**Comment by dutchTender** [comment]
question for Tina and the team: where should auto save confirmation go in "create new Attorney modal" also in the header??? should we style the new attorney modal header with the same blue color ??

**Comment by dutchTender** [comment]
implemented 90% of auto saving in our app. have questions for tina on where to put auto save info for creating new attorney. as that is in a modal, and you can't really see the header at all when you are in the modal window.
